pub const SECONDS_PER_DAY: u32 = 24 * 60 * 60;
pub const SECONDS_PER_LEDGER: u32 = 6;
pub const LEDGERS_PER_DAY: u32 = SECONDS_PER_DAY / SECONDS_PER_LEDGER;
pub const INSTANCE_THRESHOLD: u32 = 80 * LEDGERS_PER_DAY;
pub const INSTANCE_BUMP: u32 = INSTANCE_THRESHOLD + LEDGERS_PER_DAY;

pub const PERSISTENT_THRESHOLD: u32 = 120 * LEDGERS_PER_DAY;
pub const PERSISTENT_BUMP: u32 = PERSISTENT_THRESHOLD + (10 * LEDGERS_PER_DAY);

pub const MANAGER_UPGRADE_IN_QUEUE_SECONDS: u64 = 60; // NB: Intended to be upgraded
pub const MIN_MARKET_UPGRADE_IN_QUEUE_SECONDS: u64 = 60;
