pub const MAX_RESERVES: u32 = 25;

pub const SECONDS_PER_DAY: u32 = 24 * 60 * 60;
pub const SECONDS_PER_LEDGER: u32 = 6;
pub const LEDGERS_PER_DAY: u32 = SECONDS_PER_DAY / SECONDS_PER_LEDGER;
pub const INSTANCE_THRESHOLD: u32 = 80 * LEDGERS_PER_DAY;
pub const INSTANCE_BUMP: u32 = INSTANCE_THRESHOLD + LEDGERS_PER_DAY;
