[package]
name = "market_manager"
version = "1.1.0"
edition = { workspace = true }
license = { workspace = true }
publish = false

[lib]
crate-type = ["lib", "cdylib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }

[features]
deploy = []
testutils = ["soroban-sdk/testutils"]
