[package]
name = "lending"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["lib", "cdylib"]
doctest = true

[dependencies]
moderc3156 = { workspace = true }
sep-40-oracle = { workspace = true }
soroban-fixed-point-math = { workspace = true }
soroban-sdk = { workspace = true }

[dev-dependencies]
sep-40-oracle = { workspace = true, features = ["testutils"] }
soroban-sdk = { workspace = true, features = ["testutils"] }

[features]
deploy = []
testutils = ["soroban-sdk/testutils"]