[package]
name = "lending"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["lib", "cdylib"]
doctest = true

[dependencies]
soroban-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }

#[target.wasm32-unknown-unknown]
#rustflags = ["-C", "link-arg=--import-memory", "-C", "link-arg=--export-table"]
