[workspace]
resolver = "2"
members = ["contracts/*", "tests", "tests/fuzz"]

[workspace.dependencies]
moderc3156 = { git = "https://github.com/xycloo/xycloans", rev = "d9a7ae1" }
sep-40-oracle = { version = "1.2.2" }
soroban-fixed-point-math = "1.3.0"
soroban-sdk = "^22.0.8"

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

# For more information about this profile see https://soroban.stellar.org/docs/basic-tutorials/logging#cargotoml-profile
[profile.release-with-logs]
inherits = "release"
debug-assertions = true
