packages:
  - packages/*
  - 'packages/sdk/*'
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - protobufjs
  - unix-dgram
  - utf-8-validate
  - vue-demi
onlyBuiltDependencies:
  - bigint-buffer
  - bufferutil
  - keccak
  - blake-hash
  - secp256k1
  - simple-git-hooks
  - tiny-secp256k1
  - unrs-resolver
  - usb
