
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const AccountPage: typeof import("../src/components/AccountsPage/AccountPage.vue").default
export const RepayDialog: typeof import("../src/components/AccountsPage/Dialogs/RepayDialog.vue").default
export const WithdrawDialog: typeof import("../src/components/AccountsPage/Dialogs/WithdrawDialog.vue").default
export const AccountBorrowTable: typeof import("../src/components/AccountsPage/Tables/AccountBorrowTable.vue").default
export const AccountBorrowTableMobile: typeof import("../src/components/AccountsPage/Tables/AccountBorrowTableMobile.vue").default
export const AccountMultiplyTable: typeof import("../src/components/AccountsPage/Tables/AccountMultiplyTable.vue").default
export const AccountSupplyTable: typeof import("../src/components/AccountsPage/Tables/AccountSupplyTable.vue").default
export const AccountSupplyTableMobile: typeof import("../src/components/AccountsPage/Tables/AccountSupplyTableMobile.vue").default
export const AppFooter: typeof import("../src/components/AppFooter.vue").default
export const AppHeader: typeof import("../src/components/AppHeader.vue").default
export const JAccordion: typeof import("../src/components/Common/JAccordion.vue").default
export const JBtn: typeof import("../src/components/Common/JBtn.vue").default
export const JBtnGroup: typeof import("../src/components/Common/JBtnGroup.vue").default
export const JCheckbox: typeof import("../src/components/Common/JCheckbox.vue").default
export const JCircularProgress: typeof import("../src/components/Common/JCircularProgress.vue").default
export const JDialog: typeof import("../src/components/Common/JDialog.vue").default
export const JDropdown: typeof import("../src/components/Common/JDropdown.vue").default
export const JInput: typeof import("../src/components/Common/JInput.vue").default
export const JLineTab: typeof import("../src/components/Common/JLineTab.vue").default
export const JLoadingSpinner: typeof import("../src/components/Common/JLoadingSpinner.vue").default
export const JPillLabel: typeof import("../src/components/Common/JPillLabel.vue").default
export const JPopover: typeof import("../src/components/Common/JPopover.vue").default
export const JSelect: typeof import("../src/components/Common/JSelect.vue").default
export const JSelectPopover: typeof import("../src/components/Common/JSelectPopover.vue").default
export const JSkeleton: typeof import("../src/components/Common/JSkeleton.vue").default
export const JToggle: typeof import("../src/components/Common/JToggle.vue").default
export const JTooltip: typeof import("../src/components/Common/JTooltip.vue").default
export const ConnectWallet: typeof import("../src/components/ConnectWallet.vue").default
export const CopyToClipboard: typeof import("../src/components/CopyToClipboard.vue").default
export const CustomMixedChart: typeof import("../src/components/CustomMixedChart.vue").default
export const DynamicTeleport: typeof import("../src/components/DynamicTeleport.vue").default
export const FaucetMenu: typeof import("../src/components/FaucetMenu.vue").default
export const BorrowDialog: typeof import("../src/components/MarketsPage/Markets/Dialogs/BorrowDialog.vue").default
export const SupplyDialog: typeof import("../src/components/MarketsPage/Markets/Dialogs/SupplyDialog.vue").default
export const ClearFiltersBtn: typeof import("../src/components/MarketsPage/Markets/Filters/ClearFiltersBtn.vue").default
export const CollapseAllBtn: typeof import("../src/components/MarketsPage/Markets/Filters/CollapseAllBtn.vue").default
export const CollateralAssetsFilter: typeof import("../src/components/MarketsPage/Markets/Filters/CollateralAssetsFilter.vue").default
export const DebtAssetsFilter: typeof import("../src/components/MarketsPage/Markets/Filters/DebtAssetsFilter.vue").default
export const MarketSearch: typeof import("../src/components/MarketsPage/Markets/Filters/MarketSearch.vue").default
export const MarketProgress: typeof import("../src/components/MarketsPage/Markets/MarketDetailInfo/MarketProgress.vue").default
export const Markets: typeof import("../src/components/MarketsPage/Markets/Markets.vue").default
export const MyPositionsWidget: typeof import("../src/components/MarketsPage/Markets/MyPositionsWidget.vue").default
export const MarketsList: typeof import("../src/components/MarketsPage/Markets/Tables/MarketsList.vue").default
export const MarketsListMobile: typeof import("../src/components/MarketsPage/Markets/Tables/MarketsListMobile.vue").default
export const MarketsInfo: typeof import("../src/components/MarketsPage/MarketsInfo.vue").default
export const MarketsPage: typeof import("../src/components/MarketsPage/MarketsPage.vue").default
export const MultiplyDetailTop: typeof import("../src/components/MultiplyDetailsPage/MultiplyDetailTop.vue").default
export const MultiplyDetailsPage: typeof import("../src/components/MultiplyDetailsPage/MultiplyDetailsPage.vue").default
export const MultiplyOverview: typeof import("../src/components/MultiplyDetailsPage/Overview/MultiplyOverview.vue").default
export const MultiplyForm: typeof import("../src/components/MultiplyDetailsPage/Overview/Sections/MultiplyForm.vue").default
export const MultiplyHistoryChart: typeof import("../src/components/MultiplyDetailsPage/Overview/Sections/MultiplyHistoryChart.vue").default
export const MultiplyStats: typeof import("../src/components/MultiplyDetailsPage/Overview/Sections/MultiplyStats.vue").default
export const MultiplyVault: typeof import("../src/components/MultiplyDetailsPage/Overview/Sections/MultiplyVault.vue").default
export const MultiplyPosition: typeof import("../src/components/MultiplyDetailsPage/Position/MultiplyPosition.vue").default
export const RiskWarning: typeof import("../src/components/MultiplyDetailsPage/Position/RiskWarning.vue").default
export const MyMultiplyPositions: typeof import("../src/components/MultiplyDetailsPage/Position/Sections/MyMultiplyPositions.vue").default
export const MultiplyDialog: typeof import("../src/components/MultiplyPage/Dialogs/MultiplyDialog.vue").default
export const WithdrawLeverageDialog: typeof import("../src/components/MultiplyPage/Dialogs/WithdrawLeverageDialog.vue").default
export const MultiplyApyChart: typeof import("../src/components/MultiplyPage/MultiplyApyChart.vue").default
export const MultiplyPage: typeof import("../src/components/MultiplyPage/MultiplyPage.vue").default
export const MultiplySelect: typeof import("../src/components/MultiplyPage/MultiplySelect.vue").default
export const MultiplyTable: typeof import("../src/components/MultiplyPage/Tables/MultiplyTable.vue").default
export const MultiplyTableMobile: typeof import("../src/components/MultiplyPage/Tables/MultiplyTableMobile.vue").default
export const PoolHistoryChart: typeof import("../src/components/PoolDetailPage/Charts/PoolHistoryChart.vue").default
export const PoolInterestChart: typeof import("../src/components/PoolDetailPage/Charts/PoolInterestChart.vue").default
export const PoolOverview: typeof import("../src/components/PoolDetailPage/Overview/PoolOverview.vue").default
export const PoolOverviewBottomTabs: typeof import("../src/components/PoolDetailPage/Overview/PoolOverviewBottomTabs.vue").default
export const PoolDetailOverview: typeof import("../src/components/PoolDetailPage/Overview/Sections/PoolDetailOverview.vue").default
export const PoolInfoOverview: typeof import("../src/components/PoolDetailPage/Overview/Sections/PoolInfoOverview.vue").default
export const PoolSupplyBorrowOverview: typeof import("../src/components/PoolDetailPage/Overview/Sections/PoolSupplyBorrowOverview.vue").default
export const BorrowOverview: typeof import("../src/components/PoolDetailPage/Overview/Sections/SupplyBorrow/BorrowOverview.vue").default
export const SupplyOverview: typeof import("../src/components/PoolDetailPage/Overview/Sections/SupplyBorrow/SupplyOverview.vue").default
export const PoolDetailPage: typeof import("../src/components/PoolDetailPage/PoolDetailPage.vue").default
export const PoolDetailTop: typeof import("../src/components/PoolDetailPage/PoolDetailTop.vue").default
export const PoolInfoRisks: typeof import("../src/components/PoolDetailPage/PoolInfoRisks.vue").default
export const MyPosition: typeof import("../src/components/PoolDetailPage/Position/MyPosition.vue").default
export const PositionBorrowLimits: typeof import("../src/components/PoolDetailPage/Position/PositionBorrowLimits.vue").default
export const PositionOverview: typeof import("../src/components/PoolDetailPage/Position/PositionOverview.vue").default
export const PositionRiskMetrics: typeof import("../src/components/PoolDetailPage/Position/PositionRiskMetrics.vue").default
export const PositionSupplyInfo: typeof import("../src/components/PoolDetailPage/Position/PositionSupplyInfo.vue").default
export const AppSettings: typeof import("../src/components/Settings/AppSettings.vue").default
export const SettingsConnect: typeof import("../src/components/Settings/Options/SettingsConnect.vue").default
export const SettingsLanguage: typeof import("../src/components/Settings/Options/SettingsLanguage.vue").default
export const SettingsNavigation: typeof import("../src/components/Settings/Options/SettingsNavigation.vue").default
export const SettingsNetwork: typeof import("../src/components/Settings/Options/SettingsNetwork.vue").default
export const SettingsRecentActivity: typeof import("../src/components/Settings/Options/SettingsRecentActivity.vue").default
export const SettingsTheme: typeof import("../src/components/Settings/Options/SettingsTheme.vue").default
export const SettingsSidebar: typeof import("../src/components/Settings/SettingsSidebar.vue").default
export const Sidebar: typeof import("../src/components/Sidebar/Sidebar.vue").default
export const SidebarPanel: typeof import("../src/components/Sidebar/SidebarPanel.vue").default
export const BorrowTableSkeleton: typeof import("../src/components/Skeleton/BorrowTableSkeleton.vue").default
export const MarketInfoSkeleton: typeof import("../src/components/Skeleton/MarketInfoSkeleton.vue").default
export const MarketTableSkeleton: typeof import("../src/components/Skeleton/MarketTableSkeleton.vue").default
export const MarketTableSkeletonMobile: typeof import("../src/components/Skeleton/MarketTableSkeletonMobile.vue").default
export const PoolDetailSkeleton: typeof import("../src/components/Skeleton/PoolDetailSkeleton.vue").default
export const SupplyTableSkeleton: typeof import("../src/components/Skeleton/SupplyTableSkeleton.vue").default
export const TableSkeletonMobile: typeof import("../src/components/Skeleton/TableSkeletonMobile.vue").default
export const BorrowWindow: typeof import("../src/components/SupplyCard/BorrowWindow.vue").default
export const ChangePoolDialog: typeof import("../src/components/SupplyCard/ChangePoolDialog.vue").default
export const RepayWindow: typeof import("../src/components/SupplyCard/RepayWindow.vue").default
export const SupplyCard: typeof import("../src/components/SupplyCard/SupplyCard.vue").default
export const SupplyWindow: typeof import("../src/components/SupplyCard/SupplyWindow.vue").default
export const WithdrawWindow: typeof import("../src/components/SupplyCard/WithdrawWindow.vue").default
export const AddressIcon: typeof import("../src/components/Widget/AddressIcon.vue").default
export const BackBtn: typeof import("../src/components/Widget/BackBtn.vue").default
export const ChartDateFilter: typeof import("../src/components/Widget/ChartDateFilter.vue").default
export const InfoPanel: typeof import("../src/components/Widget/InfoPanel.vue").default
export const InfoTooltip: typeof import("../src/components/Widget/InfoTooltip.vue").default
export const InputWidget: typeof import("../src/components/Widget/InputWidget.vue").default
export const LightingApy: typeof import("../src/components/Widget/LightingApy.vue").default
export const LogoWithText: typeof import("../src/components/Widget/LogoWithText.vue").default
export const MarketDialogActionBtn: typeof import("../src/components/Widget/MarketDialogActionBtn.vue").default
export const MarketInfoBadge: typeof import("../src/components/Widget/MarketInfoBadge.vue").default
export const MarketInfoDetailCard: typeof import("../src/components/Widget/MarketInfoDetailCard.vue").default
export const MetricIndicator: typeof import("../src/components/Widget/MetricIndicator.vue").default
export const PoolStatus: typeof import("../src/components/Widget/PoolStatus.vue").default
export const ReloadCoundown: typeof import("../src/components/Widget/ReloadCoundown.vue").default
export const TableMobileCard: typeof import("../src/components/Widget/TableMobileCard.vue").default
export const TotalCard: typeof import("../src/components/Widget/TotalCard.vue").default
export const WarningBlock: typeof import("../src/components/Widget/WarningBlock.vue").default
export const NuxtWelcome: typeof import("../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/welcome.vue").default
export const NuxtLayout: typeof import("../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/nuxt-layout").default
export const NuxtErrorBoundary: typeof import("../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default
export const ClientOnly: typeof import("../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/client-only").default
export const DevOnly: typeof import("../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/dev-only").default
export const ServerPlaceholder: typeof import("../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/server-placeholder").default
export const NuxtLink: typeof import("../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/nuxt-link").default
export const NuxtLoadingIndicator: typeof import("../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default
export const NuxtTime: typeof import("../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/nuxt-time.vue").default
export const NuxtRouteAnnouncer: typeof import("../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/nuxt-route-announcer").default
export const NuxtImg: typeof import("../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtImg
export const NuxtPicture: typeof import("../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtPicture
export const BAccordion: typeof import("bootstrap-vue-next/components/BAccordion").BAccordion
export const BAccordionItem: typeof import("bootstrap-vue-next/components/BAccordion").BAccordionItem
export const BAlert: typeof import("bootstrap-vue-next/components/BAlert").BAlert
export const BAvatar: typeof import("bootstrap-vue-next/components/BAvatar").BAvatar
export const BAvatarGroup: typeof import("bootstrap-vue-next/components/BAvatar").BAvatarGroup
export const BBadge: typeof import("bootstrap-vue-next/components/BBadge").BBadge
export const BBreadcrumb: typeof import("bootstrap-vue-next/components/BBreadcrumb").BBreadcrumb
export const BBreadcrumbItem: typeof import("bootstrap-vue-next/components/BBreadcrumb").BBreadcrumbItem
export const BButton: typeof import("bootstrap-vue-next/components/BButton").BButton
export const BButtonGroup: typeof import("bootstrap-vue-next/components/BButton").BButtonGroup
export const BButtonToolbar: typeof import("bootstrap-vue-next/components/BButton").BButtonToolbar
export const BCloseButton: typeof import("bootstrap-vue-next/components/BButton").BCloseButton
export const BCard: typeof import("bootstrap-vue-next/components/BCard").BCard
export const BCardBody: typeof import("bootstrap-vue-next/components/BCard").BCardBody
export const BCardFooter: typeof import("bootstrap-vue-next/components/BCard").BCardFooter
export const BCardGroup: typeof import("bootstrap-vue-next/components/BCard").BCardGroup
export const BCardHeader: typeof import("bootstrap-vue-next/components/BCard").BCardHeader
export const BCardImg: typeof import("bootstrap-vue-next/components/BCard").BCardImg
export const BCardSubtitle: typeof import("bootstrap-vue-next/components/BCard").BCardSubtitle
export const BCardText: typeof import("bootstrap-vue-next/components/BCard").BCardText
export const BCardTitle: typeof import("bootstrap-vue-next/components/BCard").BCardTitle
export const BCarousel: typeof import("bootstrap-vue-next/components/BCarousel").BCarousel
export const BCarouselSlide: typeof import("bootstrap-vue-next/components/BCarousel").BCarouselSlide
export const BCol: typeof import("bootstrap-vue-next/components/BContainer").BCol
export const BCollapse: typeof import("bootstrap-vue-next/components/BCollapse").BCollapse
export const BContainer: typeof import("bootstrap-vue-next/components/BContainer").BContainer
export const BDropdown: typeof import("bootstrap-vue-next/components/BDropdown").BDropdown
export const BDropdownDivider: typeof import("bootstrap-vue-next/components/BDropdown").BDropdownDivider
export const BDropdownForm: typeof import("bootstrap-vue-next/components/BDropdown").BDropdownForm
export const BDropdownGroup: typeof import("bootstrap-vue-next/components/BDropdown").BDropdownGroup
export const BDropdownHeader: typeof import("bootstrap-vue-next/components/BDropdown").BDropdownHeader
export const BDropdownItem: typeof import("bootstrap-vue-next/components/BDropdown").BDropdownItem
export const BDropdownItemButton: typeof import("bootstrap-vue-next/components/BDropdown").BDropdownItemButton
export const BDropdownText: typeof import("bootstrap-vue-next/components/BDropdown").BDropdownText
export const BForm: typeof import("bootstrap-vue-next/components/BForm").BForm
export const BFormCheckbox: typeof import("bootstrap-vue-next/components/BFormCheckbox").BFormCheckbox
export const BFormCheckboxGroup: typeof import("bootstrap-vue-next/components/BFormCheckbox").BFormCheckboxGroup
export const BFormDatalist: typeof import("bootstrap-vue-next/components/BForm").BFormDatalist
export const BFormFile: typeof import("bootstrap-vue-next/components/BFormFile").BFormFile
export const BFormFloatingLabel: typeof import("bootstrap-vue-next/components/BForm").BFormFloatingLabel
export const BFormGroup: typeof import("bootstrap-vue-next/components/BFormGroup").BFormGroup
export const BFormInput: typeof import("bootstrap-vue-next/components/BFormInput").BFormInput
export const BFormInvalidFeedback: typeof import("bootstrap-vue-next/components/BForm").BFormInvalidFeedback
export const BFormRadio: typeof import("bootstrap-vue-next/components/BFormRadio").BFormRadio
export const BFormRadioGroup: typeof import("bootstrap-vue-next/components/BFormRadio").BFormRadioGroup
export const BFormRating: typeof import("bootstrap-vue-next/components/BFormRating").BFormRating
export const BFormRow: typeof import("bootstrap-vue-next/components/BForm").BFormRow
export const BFormSelect: typeof import("bootstrap-vue-next/components/BFormSelect").BFormSelect
export const BFormSelectOption: typeof import("bootstrap-vue-next/components/BFormSelect").BFormSelectOption
export const BFormSelectOptionGroup: typeof import("bootstrap-vue-next/components/BFormSelect").BFormSelectOptionGroup
export const BFormSpinbutton: typeof import("bootstrap-vue-next/components/BFormSpinbutton").BFormSpinbutton
export const BFormTag: typeof import("bootstrap-vue-next/components/BFormTags").BFormTag
export const BFormTags: typeof import("bootstrap-vue-next/components/BFormTags").BFormTags
export const BFormText: typeof import("bootstrap-vue-next/components/BForm").BFormText
export const BFormTextarea: typeof import("bootstrap-vue-next/components/BFormTextarea").BFormTextarea
export const BFormValidFeedback: typeof import("bootstrap-vue-next/components/BForm").BFormValidFeedback
export const BImg: typeof import("bootstrap-vue-next/components/BImg").BImg
export const BInput: typeof import("bootstrap-vue-next/components/BFormInput").BInput
export const BInputGroup: typeof import("bootstrap-vue-next/components/BInputGroup").BInputGroup
export const BInputGroupText: typeof import("bootstrap-vue-next/components/BInputGroup").BInputGroupText
export const BListGroup: typeof import("bootstrap-vue-next/components/BListGroup").BListGroup
export const BListGroupItem: typeof import("bootstrap-vue-next/components/BListGroup").BListGroupItem
export const BModal: typeof import("bootstrap-vue-next/components/BModal").BModal
export const BModalOrchestrator: typeof import("bootstrap-vue-next/components/BModal").BModalOrchestrator
export const BNav: typeof import("bootstrap-vue-next/components/BNav").BNav
export const BNavForm: typeof import("bootstrap-vue-next/components/BNav").BNavForm
export const BNavItem: typeof import("bootstrap-vue-next/components/BNav").BNavItem
export const BNavItemDropdown: typeof import("bootstrap-vue-next/components/BNav").BNavItemDropdown
export const BNavText: typeof import("bootstrap-vue-next/components/BNav").BNavText
export const BNavbar: typeof import("bootstrap-vue-next/components/BNavbar").BNavbar
export const BNavbarBrand: typeof import("bootstrap-vue-next/components/BNavbar").BNavbarBrand
export const BNavbarNav: typeof import("bootstrap-vue-next/components/BNavbar").BNavbarNav
export const BNavbarToggle: typeof import("bootstrap-vue-next/components/BNavbar").BNavbarToggle
export const BOffcanvas: typeof import("bootstrap-vue-next/components/BOffcanvas").BOffcanvas
export const BOverlay: typeof import("bootstrap-vue-next/components/BOverlay").BOverlay
export const BPagination: typeof import("bootstrap-vue-next/components/BPagination").BPagination
export const BPlaceholder: typeof import("bootstrap-vue-next/components/BPlaceholder").BPlaceholder
export const BPlaceholderButton: typeof import("bootstrap-vue-next/components/BPlaceholder").BPlaceholderButton
export const BPlaceholderCard: typeof import("bootstrap-vue-next/components/BPlaceholder").BPlaceholderCard
export const BPlaceholderTable: typeof import("bootstrap-vue-next/components/BPlaceholder").BPlaceholderTable
export const BPlaceholderWrapper: typeof import("bootstrap-vue-next/components/BPlaceholder").BPlaceholderWrapper
export const BPopover: typeof import("bootstrap-vue-next/components/BPopover").BPopover
export const BProgress: typeof import("bootstrap-vue-next/components/BProgress").BProgress
export const BRow: typeof import("bootstrap-vue-next/components/BContainer").BRow
export const BSpinner: typeof import("bootstrap-vue-next/components/BSpinner").BSpinner
export const BTab: typeof import("bootstrap-vue-next/components/BTabs").BTab
export const BTabs: typeof import("bootstrap-vue-next/components/BTabs").BTabs
export const BToast: typeof import("bootstrap-vue-next/components/BToast").BToast
export const BToastOrchestrator: typeof import("bootstrap-vue-next/components/BToast").BToastOrchestrator
export const BTooltip: typeof import("bootstrap-vue-next/components/BTooltip").BTooltip
export const BLink: typeof import("bootstrap-vue-next/components/BLink").BLink
export const BProgressBar: typeof import("bootstrap-vue-next/components/BProgress").BProgressBar
export const BTableSimple: typeof import("bootstrap-vue-next/components/BTable").BTableSimple
export const BTableLite: typeof import("bootstrap-vue-next/components/BTable").BTableLite
export const BTable: typeof import("bootstrap-vue-next/components/BTable").BTable
export const BTbody: typeof import("bootstrap-vue-next/components/BTable").BTbody
export const BTd: typeof import("bootstrap-vue-next/components/BTable").BTd
export const BTh: typeof import("bootstrap-vue-next/components/BTable").BTh
export const BThead: typeof import("bootstrap-vue-next/components/BTable").BThead
export const BTfoot: typeof import("bootstrap-vue-next/components/BTable").BTfoot
export const BTr: typeof import("bootstrap-vue-next/components/BTable").BTr
export const BPopoverOrchestrator: typeof import("bootstrap-vue-next/components/BPopover").BPopoverOrchestrator
export const NuxtLinkLocale: typeof import("../../../node_modules/.pnpm/@nuxtjs+i18n@10.2.1_@vue+compiler-dom@3.5.27_db0@0.3.4_eslint@9.39.2_jiti@2.6.1__idb-ke_d844bff0289b9fea1b2ee74a046c285f/node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale").default
export const SwitchLocalePathLink: typeof import("../../../node_modules/.pnpm/@nuxtjs+i18n@10.2.1_@vue+compiler-dom@3.5.27_db0@0.3.4_eslint@9.39.2_jiti@2.6.1__idb-ke_d844bff0289b9fea1b2ee74a046c285f/node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink").default
export const VitePwaManifest: typeof import("../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.0_magicast@0.5.1_vite@7.3.1_@types+node@24.10.9_jiti@2.6.1_sass-embe_3c67240a609a9e48fa8175d737b11896/node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest").default
export const NuxtPwaManifest: typeof import("../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.0_magicast@0.5.1_vite@7.3.1_@types+node@24.10.9_jiti@2.6.1_sass-embe_3c67240a609a9e48fa8175d737b11896/node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest").default
export const NuxtPwaAssets: typeof import("../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.0_magicast@0.5.1_vite@7.3.1_@types+node@24.10.9_jiti@2.6.1_sass-embe_3c67240a609a9e48fa8175d737b11896/node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets").default
export const PwaAppleImage: typeof import("../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.0_magicast@0.5.1_vite@7.3.1_@types+node@24.10.9_jiti@2.6.1_sass-embe_3c67240a609a9e48fa8175d737b11896/node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaAppleImage").default
export const PwaAppleSplashScreenImage: typeof import("../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.0_magicast@0.5.1_vite@7.3.1_@types+node@24.10.9_jiti@2.6.1_sass-embe_3c67240a609a9e48fa8175d737b11896/node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaAppleSplashScreenImage").default
export const PwaFaviconImage: typeof import("../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.0_magicast@0.5.1_vite@7.3.1_@types+node@24.10.9_jiti@2.6.1_sass-embe_3c67240a609a9e48fa8175d737b11896/node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaFaviconImage").default
export const PwaMaskableImage: typeof import("../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.0_magicast@0.5.1_vite@7.3.1_@types+node@24.10.9_jiti@2.6.1_sass-embe_3c67240a609a9e48fa8175d737b11896/node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaMaskableImage").default
export const PwaTransparentImage: typeof import("../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.0_magicast@0.5.1_vite@7.3.1_@types+node@24.10.9_jiti@2.6.1_sass-embe_3c67240a609a9e48fa8175d737b11896/node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaTransparentImage").default
export const NuxtPage: typeof import("../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/pages/runtime/page").default
export const NoScript: typeof import("../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/head/runtime/components").NoScript
export const Link: typeof import("../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/head/runtime/components").Link
export const Base: typeof import("../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/head/runtime/components").Base
export const Title: typeof import("../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/head/runtime/components").Title
export const Meta: typeof import("../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/head/runtime/components").Meta
export const Style: typeof import("../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/head/runtime/components").Style
export const Head: typeof import("../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/head/runtime/components").Head
export const Html: typeof import("../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/head/runtime/components").Html
export const Body: typeof import("../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/head/runtime/components").Body
export const NuxtIsland: typeof import("../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/nuxt-island").default
export const LazyAccountPage: LazyComponent<typeof import("../src/components/AccountsPage/AccountPage.vue").default>
export const LazyRepayDialog: LazyComponent<typeof import("../src/components/AccountsPage/Dialogs/RepayDialog.vue").default>
export const LazyWithdrawDialog: LazyComponent<typeof import("../src/components/AccountsPage/Dialogs/WithdrawDialog.vue").default>
export const LazyAccountBorrowTable: LazyComponent<typeof import("../src/components/AccountsPage/Tables/AccountBorrowTable.vue").default>
export const LazyAccountBorrowTableMobile: LazyComponent<typeof import("../src/components/AccountsPage/Tables/AccountBorrowTableMobile.vue").default>
export const LazyAccountMultiplyTable: LazyComponent<typeof import("../src/components/AccountsPage/Tables/AccountMultiplyTable.vue").default>
export const LazyAccountSupplyTable: LazyComponent<typeof import("../src/components/AccountsPage/Tables/AccountSupplyTable.vue").default>
export const LazyAccountSupplyTableMobile: LazyComponent<typeof import("../src/components/AccountsPage/Tables/AccountSupplyTableMobile.vue").default>
export const LazyAppFooter: LazyComponent<typeof import("../src/components/AppFooter.vue").default>
export const LazyAppHeader: LazyComponent<typeof import("../src/components/AppHeader.vue").default>
export const LazyJAccordion: LazyComponent<typeof import("../src/components/Common/JAccordion.vue").default>
export const LazyJBtn: LazyComponent<typeof import("../src/components/Common/JBtn.vue").default>
export const LazyJBtnGroup: LazyComponent<typeof import("../src/components/Common/JBtnGroup.vue").default>
export const LazyJCheckbox: LazyComponent<typeof import("../src/components/Common/JCheckbox.vue").default>
export const LazyJCircularProgress: LazyComponent<typeof import("../src/components/Common/JCircularProgress.vue").default>
export const LazyJDialog: LazyComponent<typeof import("../src/components/Common/JDialog.vue").default>
export const LazyJDropdown: LazyComponent<typeof import("../src/components/Common/JDropdown.vue").default>
export const LazyJInput: LazyComponent<typeof import("../src/components/Common/JInput.vue").default>
export const LazyJLineTab: LazyComponent<typeof import("../src/components/Common/JLineTab.vue").default>
export const LazyJLoadingSpinner: LazyComponent<typeof import("../src/components/Common/JLoadingSpinner.vue").default>
export const LazyJPillLabel: LazyComponent<typeof import("../src/components/Common/JPillLabel.vue").default>
export const LazyJPopover: LazyComponent<typeof import("../src/components/Common/JPopover.vue").default>
export const LazyJSelect: LazyComponent<typeof import("../src/components/Common/JSelect.vue").default>
export const LazyJSelectPopover: LazyComponent<typeof import("../src/components/Common/JSelectPopover.vue").default>
export const LazyJSkeleton: LazyComponent<typeof import("../src/components/Common/JSkeleton.vue").default>
export const LazyJToggle: LazyComponent<typeof import("../src/components/Common/JToggle.vue").default>
export const LazyJTooltip: LazyComponent<typeof import("../src/components/Common/JTooltip.vue").default>
export const LazyConnectWallet: LazyComponent<typeof import("../src/components/ConnectWallet.vue").default>
export const LazyCopyToClipboard: LazyComponent<typeof import("../src/components/CopyToClipboard.vue").default>
export const LazyCustomMixedChart: LazyComponent<typeof import("../src/components/CustomMixedChart.vue").default>
export const LazyDynamicTeleport: LazyComponent<typeof import("../src/components/DynamicTeleport.vue").default>
export const LazyFaucetMenu: LazyComponent<typeof import("../src/components/FaucetMenu.vue").default>
export const LazyBorrowDialog: LazyComponent<typeof import("../src/components/MarketsPage/Markets/Dialogs/BorrowDialog.vue").default>
export const LazySupplyDialog: LazyComponent<typeof import("../src/components/MarketsPage/Markets/Dialogs/SupplyDialog.vue").default>
export const LazyClearFiltersBtn: LazyComponent<typeof import("../src/components/MarketsPage/Markets/Filters/ClearFiltersBtn.vue").default>
export const LazyCollapseAllBtn: LazyComponent<typeof import("../src/components/MarketsPage/Markets/Filters/CollapseAllBtn.vue").default>
export const LazyCollateralAssetsFilter: LazyComponent<typeof import("../src/components/MarketsPage/Markets/Filters/CollateralAssetsFilter.vue").default>
export const LazyDebtAssetsFilter: LazyComponent<typeof import("../src/components/MarketsPage/Markets/Filters/DebtAssetsFilter.vue").default>
export const LazyMarketSearch: LazyComponent<typeof import("../src/components/MarketsPage/Markets/Filters/MarketSearch.vue").default>
export const LazyMarketProgress: LazyComponent<typeof import("../src/components/MarketsPage/Markets/MarketDetailInfo/MarketProgress.vue").default>
export const LazyMarkets: LazyComponent<typeof import("../src/components/MarketsPage/Markets/Markets.vue").default>
export const LazyMyPositionsWidget: LazyComponent<typeof import("../src/components/MarketsPage/Markets/MyPositionsWidget.vue").default>
export const LazyMarketsList: LazyComponent<typeof import("../src/components/MarketsPage/Markets/Tables/MarketsList.vue").default>
export const LazyMarketsListMobile: LazyComponent<typeof import("../src/components/MarketsPage/Markets/Tables/MarketsListMobile.vue").default>
export const LazyMarketsInfo: LazyComponent<typeof import("../src/components/MarketsPage/MarketsInfo.vue").default>
export const LazyMarketsPage: LazyComponent<typeof import("../src/components/MarketsPage/MarketsPage.vue").default>
export const LazyMultiplyDetailTop: LazyComponent<typeof import("../src/components/MultiplyDetailsPage/MultiplyDetailTop.vue").default>
export const LazyMultiplyDetailsPage: LazyComponent<typeof import("../src/components/MultiplyDetailsPage/MultiplyDetailsPage.vue").default>
export const LazyMultiplyOverview: LazyComponent<typeof import("../src/components/MultiplyDetailsPage/Overview/MultiplyOverview.vue").default>
export const LazyMultiplyForm: LazyComponent<typeof import("../src/components/MultiplyDetailsPage/Overview/Sections/MultiplyForm.vue").default>
export const LazyMultiplyHistoryChart: LazyComponent<typeof import("../src/components/MultiplyDetailsPage/Overview/Sections/MultiplyHistoryChart.vue").default>
export const LazyMultiplyStats: LazyComponent<typeof import("../src/components/MultiplyDetailsPage/Overview/Sections/MultiplyStats.vue").default>
export const LazyMultiplyVault: LazyComponent<typeof import("../src/components/MultiplyDetailsPage/Overview/Sections/MultiplyVault.vue").default>
export const LazyMultiplyPosition: LazyComponent<typeof import("../src/components/MultiplyDetailsPage/Position/MultiplyPosition.vue").default>
export const LazyRiskWarning: LazyComponent<typeof import("../src/components/MultiplyDetailsPage/Position/RiskWarning.vue").default>
export const LazyMyMultiplyPositions: LazyComponent<typeof import("../src/components/MultiplyDetailsPage/Position/Sections/MyMultiplyPositions.vue").default>
export const LazyMultiplyDialog: LazyComponent<typeof import("../src/components/MultiplyPage/Dialogs/MultiplyDialog.vue").default>
export const LazyWithdrawLeverageDialog: LazyComponent<typeof import("../src/components/MultiplyPage/Dialogs/WithdrawLeverageDialog.vue").default>
export const LazyMultiplyApyChart: LazyComponent<typeof import("../src/components/MultiplyPage/MultiplyApyChart.vue").default>
export const LazyMultiplyPage: LazyComponent<typeof import("../src/components/MultiplyPage/MultiplyPage.vue").default>
export const LazyMultiplySelect: LazyComponent<typeof import("../src/components/MultiplyPage/MultiplySelect.vue").default>
export const LazyMultiplyTable: LazyComponent<typeof import("../src/components/MultiplyPage/Tables/MultiplyTable.vue").default>
export const LazyMultiplyTableMobile: LazyComponent<typeof import("../src/components/MultiplyPage/Tables/MultiplyTableMobile.vue").default>
export const LazyPoolHistoryChart: LazyComponent<typeof import("../src/components/PoolDetailPage/Charts/PoolHistoryChart.vue").default>
export const LazyPoolInterestChart: LazyComponent<typeof import("../src/components/PoolDetailPage/Charts/PoolInterestChart.vue").default>
export const LazyPoolOverview: LazyComponent<typeof import("../src/components/PoolDetailPage/Overview/PoolOverview.vue").default>
export const LazyPoolOverviewBottomTabs: LazyComponent<typeof import("../src/components/PoolDetailPage/Overview/PoolOverviewBottomTabs.vue").default>
export const LazyPoolDetailOverview: LazyComponent<typeof import("../src/components/PoolDetailPage/Overview/Sections/PoolDetailOverview.vue").default>
export const LazyPoolInfoOverview: LazyComponent<typeof import("../src/components/PoolDetailPage/Overview/Sections/PoolInfoOverview.vue").default>
export const LazyPoolSupplyBorrowOverview: LazyComponent<typeof import("../src/components/PoolDetailPage/Overview/Sections/PoolSupplyBorrowOverview.vue").default>
export const LazyBorrowOverview: LazyComponent<typeof import("../src/components/PoolDetailPage/Overview/Sections/SupplyBorrow/BorrowOverview.vue").default>
export const LazySupplyOverview: LazyComponent<typeof import("../src/components/PoolDetailPage/Overview/Sections/SupplyBorrow/SupplyOverview.vue").default>
export const LazyPoolDetailPage: LazyComponent<typeof import("../src/components/PoolDetailPage/PoolDetailPage.vue").default>
export const LazyPoolDetailTop: LazyComponent<typeof import("../src/components/PoolDetailPage/PoolDetailTop.vue").default>
export const LazyPoolInfoRisks: LazyComponent<typeof import("../src/components/PoolDetailPage/PoolInfoRisks.vue").default>
export const LazyMyPosition: LazyComponent<typeof import("../src/components/PoolDetailPage/Position/MyPosition.vue").default>
export const LazyPositionBorrowLimits: LazyComponent<typeof import("../src/components/PoolDetailPage/Position/PositionBorrowLimits.vue").default>
export const LazyPositionOverview: LazyComponent<typeof import("../src/components/PoolDetailPage/Position/PositionOverview.vue").default>
export const LazyPositionRiskMetrics: LazyComponent<typeof import("../src/components/PoolDetailPage/Position/PositionRiskMetrics.vue").default>
export const LazyPositionSupplyInfo: LazyComponent<typeof import("../src/components/PoolDetailPage/Position/PositionSupplyInfo.vue").default>
export const LazyAppSettings: LazyComponent<typeof import("../src/components/Settings/AppSettings.vue").default>
export const LazySettingsConnect: LazyComponent<typeof import("../src/components/Settings/Options/SettingsConnect.vue").default>
export const LazySettingsLanguage: LazyComponent<typeof import("../src/components/Settings/Options/SettingsLanguage.vue").default>
export const LazySettingsNavigation: LazyComponent<typeof import("../src/components/Settings/Options/SettingsNavigation.vue").default>
export const LazySettingsNetwork: LazyComponent<typeof import("../src/components/Settings/Options/SettingsNetwork.vue").default>
export const LazySettingsRecentActivity: LazyComponent<typeof import("../src/components/Settings/Options/SettingsRecentActivity.vue").default>
export const LazySettingsTheme: LazyComponent<typeof import("../src/components/Settings/Options/SettingsTheme.vue").default>
export const LazySettingsSidebar: LazyComponent<typeof import("../src/components/Settings/SettingsSidebar.vue").default>
export const LazySidebar: LazyComponent<typeof import("../src/components/Sidebar/Sidebar.vue").default>
export const LazySidebarPanel: LazyComponent<typeof import("../src/components/Sidebar/SidebarPanel.vue").default>
export const LazyBorrowTableSkeleton: LazyComponent<typeof import("../src/components/Skeleton/BorrowTableSkeleton.vue").default>
export const LazyMarketInfoSkeleton: LazyComponent<typeof import("../src/components/Skeleton/MarketInfoSkeleton.vue").default>
export const LazyMarketTableSkeleton: LazyComponent<typeof import("../src/components/Skeleton/MarketTableSkeleton.vue").default>
export const LazyMarketTableSkeletonMobile: LazyComponent<typeof import("../src/components/Skeleton/MarketTableSkeletonMobile.vue").default>
export const LazyPoolDetailSkeleton: LazyComponent<typeof import("../src/components/Skeleton/PoolDetailSkeleton.vue").default>
export const LazySupplyTableSkeleton: LazyComponent<typeof import("../src/components/Skeleton/SupplyTableSkeleton.vue").default>
export const LazyTableSkeletonMobile: LazyComponent<typeof import("../src/components/Skeleton/TableSkeletonMobile.vue").default>
export const LazyBorrowWindow: LazyComponent<typeof import("../src/components/SupplyCard/BorrowWindow.vue").default>
export const LazyChangePoolDialog: LazyComponent<typeof import("../src/components/SupplyCard/ChangePoolDialog.vue").default>
export const LazyRepayWindow: LazyComponent<typeof import("../src/components/SupplyCard/RepayWindow.vue").default>
export const LazySupplyCard: LazyComponent<typeof import("../src/components/SupplyCard/SupplyCard.vue").default>
export const LazySupplyWindow: LazyComponent<typeof import("../src/components/SupplyCard/SupplyWindow.vue").default>
export const LazyWithdrawWindow: LazyComponent<typeof import("../src/components/SupplyCard/WithdrawWindow.vue").default>
export const LazyAddressIcon: LazyComponent<typeof import("../src/components/Widget/AddressIcon.vue").default>
export const LazyBackBtn: LazyComponent<typeof import("../src/components/Widget/BackBtn.vue").default>
export const LazyChartDateFilter: LazyComponent<typeof import("../src/components/Widget/ChartDateFilter.vue").default>
export const LazyInfoPanel: LazyComponent<typeof import("../src/components/Widget/InfoPanel.vue").default>
export const LazyInfoTooltip: LazyComponent<typeof import("../src/components/Widget/InfoTooltip.vue").default>
export const LazyInputWidget: LazyComponent<typeof import("../src/components/Widget/InputWidget.vue").default>
export const LazyLightingApy: LazyComponent<typeof import("../src/components/Widget/LightingApy.vue").default>
export const LazyLogoWithText: LazyComponent<typeof import("../src/components/Widget/LogoWithText.vue").default>
export const LazyMarketDialogActionBtn: LazyComponent<typeof import("../src/components/Widget/MarketDialogActionBtn.vue").default>
export const LazyMarketInfoBadge: LazyComponent<typeof import("../src/components/Widget/MarketInfoBadge.vue").default>
export const LazyMarketInfoDetailCard: LazyComponent<typeof import("../src/components/Widget/MarketInfoDetailCard.vue").default>
export const LazyMetricIndicator: LazyComponent<typeof import("../src/components/Widget/MetricIndicator.vue").default>
export const LazyPoolStatus: LazyComponent<typeof import("../src/components/Widget/PoolStatus.vue").default>
export const LazyReloadCoundown: LazyComponent<typeof import("../src/components/Widget/ReloadCoundown.vue").default>
export const LazyTableMobileCard: LazyComponent<typeof import("../src/components/Widget/TableMobileCard.vue").default>
export const LazyTotalCard: LazyComponent<typeof import("../src/components/Widget/TotalCard.vue").default>
export const LazyWarningBlock: LazyComponent<typeof import("../src/components/Widget/WarningBlock.vue").default>
export const LazyNuxtWelcome: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/welcome.vue").default>
export const LazyNuxtLayout: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/nuxt-layout").default>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default>
export const LazyClientOnly: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/client-only").default>
export const LazyDevOnly: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/dev-only").default>
export const LazyServerPlaceholder: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/server-placeholder").default>
export const LazyNuxtLink: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/nuxt-link").default>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default>
export const LazyNuxtTime: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/nuxt-time.vue").default>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/nuxt-route-announcer").default>
export const LazyNuxtImg: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtImg>
export const LazyNuxtPicture: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtPicture>
export const LazyBAccordion: LazyComponent<typeof import("bootstrap-vue-next/components/BAccordion").BAccordion>
export const LazyBAccordionItem: LazyComponent<typeof import("bootstrap-vue-next/components/BAccordion").BAccordionItem>
export const LazyBAlert: LazyComponent<typeof import("bootstrap-vue-next/components/BAlert").BAlert>
export const LazyBAvatar: LazyComponent<typeof import("bootstrap-vue-next/components/BAvatar").BAvatar>
export const LazyBAvatarGroup: LazyComponent<typeof import("bootstrap-vue-next/components/BAvatar").BAvatarGroup>
export const LazyBBadge: LazyComponent<typeof import("bootstrap-vue-next/components/BBadge").BBadge>
export const LazyBBreadcrumb: LazyComponent<typeof import("bootstrap-vue-next/components/BBreadcrumb").BBreadcrumb>
export const LazyBBreadcrumbItem: LazyComponent<typeof import("bootstrap-vue-next/components/BBreadcrumb").BBreadcrumbItem>
export const LazyBButton: LazyComponent<typeof import("bootstrap-vue-next/components/BButton").BButton>
export const LazyBButtonGroup: LazyComponent<typeof import("bootstrap-vue-next/components/BButton").BButtonGroup>
export const LazyBButtonToolbar: LazyComponent<typeof import("bootstrap-vue-next/components/BButton").BButtonToolbar>
export const LazyBCloseButton: LazyComponent<typeof import("bootstrap-vue-next/components/BButton").BCloseButton>
export const LazyBCard: LazyComponent<typeof import("bootstrap-vue-next/components/BCard").BCard>
export const LazyBCardBody: LazyComponent<typeof import("bootstrap-vue-next/components/BCard").BCardBody>
export const LazyBCardFooter: LazyComponent<typeof import("bootstrap-vue-next/components/BCard").BCardFooter>
export const LazyBCardGroup: LazyComponent<typeof import("bootstrap-vue-next/components/BCard").BCardGroup>
export const LazyBCardHeader: LazyComponent<typeof import("bootstrap-vue-next/components/BCard").BCardHeader>
export const LazyBCardImg: LazyComponent<typeof import("bootstrap-vue-next/components/BCard").BCardImg>
export const LazyBCardSubtitle: LazyComponent<typeof import("bootstrap-vue-next/components/BCard").BCardSubtitle>
export const LazyBCardText: LazyComponent<typeof import("bootstrap-vue-next/components/BCard").BCardText>
export const LazyBCardTitle: LazyComponent<typeof import("bootstrap-vue-next/components/BCard").BCardTitle>
export const LazyBCarousel: LazyComponent<typeof import("bootstrap-vue-next/components/BCarousel").BCarousel>
export const LazyBCarouselSlide: LazyComponent<typeof import("bootstrap-vue-next/components/BCarousel").BCarouselSlide>
export const LazyBCol: LazyComponent<typeof import("bootstrap-vue-next/components/BContainer").BCol>
export const LazyBCollapse: LazyComponent<typeof import("bootstrap-vue-next/components/BCollapse").BCollapse>
export const LazyBContainer: LazyComponent<typeof import("bootstrap-vue-next/components/BContainer").BContainer>
export const LazyBDropdown: LazyComponent<typeof import("bootstrap-vue-next/components/BDropdown").BDropdown>
export const LazyBDropdownDivider: LazyComponent<typeof import("bootstrap-vue-next/components/BDropdown").BDropdownDivider>
export const LazyBDropdownForm: LazyComponent<typeof import("bootstrap-vue-next/components/BDropdown").BDropdownForm>
export const LazyBDropdownGroup: LazyComponent<typeof import("bootstrap-vue-next/components/BDropdown").BDropdownGroup>
export const LazyBDropdownHeader: LazyComponent<typeof import("bootstrap-vue-next/components/BDropdown").BDropdownHeader>
export const LazyBDropdownItem: LazyComponent<typeof import("bootstrap-vue-next/components/BDropdown").BDropdownItem>
export const LazyBDropdownItemButton: LazyComponent<typeof import("bootstrap-vue-next/components/BDropdown").BDropdownItemButton>
export const LazyBDropdownText: LazyComponent<typeof import("bootstrap-vue-next/components/BDropdown").BDropdownText>
export const LazyBForm: LazyComponent<typeof import("bootstrap-vue-next/components/BForm").BForm>
export const LazyBFormCheckbox: LazyComponent<typeof import("bootstrap-vue-next/components/BFormCheckbox").BFormCheckbox>
export const LazyBFormCheckboxGroup: LazyComponent<typeof import("bootstrap-vue-next/components/BFormCheckbox").BFormCheckboxGroup>
export const LazyBFormDatalist: LazyComponent<typeof import("bootstrap-vue-next/components/BForm").BFormDatalist>
export const LazyBFormFile: LazyComponent<typeof import("bootstrap-vue-next/components/BFormFile").BFormFile>
export const LazyBFormFloatingLabel: LazyComponent<typeof import("bootstrap-vue-next/components/BForm").BFormFloatingLabel>
export const LazyBFormGroup: LazyComponent<typeof import("bootstrap-vue-next/components/BFormGroup").BFormGroup>
export const LazyBFormInput: LazyComponent<typeof import("bootstrap-vue-next/components/BFormInput").BFormInput>
export const LazyBFormInvalidFeedback: LazyComponent<typeof import("bootstrap-vue-next/components/BForm").BFormInvalidFeedback>
export const LazyBFormRadio: LazyComponent<typeof import("bootstrap-vue-next/components/BFormRadio").BFormRadio>
export const LazyBFormRadioGroup: LazyComponent<typeof import("bootstrap-vue-next/components/BFormRadio").BFormRadioGroup>
export const LazyBFormRating: LazyComponent<typeof import("bootstrap-vue-next/components/BFormRating").BFormRating>
export const LazyBFormRow: LazyComponent<typeof import("bootstrap-vue-next/components/BForm").BFormRow>
export const LazyBFormSelect: LazyComponent<typeof import("bootstrap-vue-next/components/BFormSelect").BFormSelect>
export const LazyBFormSelectOption: LazyComponent<typeof import("bootstrap-vue-next/components/BFormSelect").BFormSelectOption>
export const LazyBFormSelectOptionGroup: LazyComponent<typeof import("bootstrap-vue-next/components/BFormSelect").BFormSelectOptionGroup>
export const LazyBFormSpinbutton: LazyComponent<typeof import("bootstrap-vue-next/components/BFormSpinbutton").BFormSpinbutton>
export const LazyBFormTag: LazyComponent<typeof import("bootstrap-vue-next/components/BFormTags").BFormTag>
export const LazyBFormTags: LazyComponent<typeof import("bootstrap-vue-next/components/BFormTags").BFormTags>
export const LazyBFormText: LazyComponent<typeof import("bootstrap-vue-next/components/BForm").BFormText>
export const LazyBFormTextarea: LazyComponent<typeof import("bootstrap-vue-next/components/BFormTextarea").BFormTextarea>
export const LazyBFormValidFeedback: LazyComponent<typeof import("bootstrap-vue-next/components/BForm").BFormValidFeedback>
export const LazyBImg: LazyComponent<typeof import("bootstrap-vue-next/components/BImg").BImg>
export const LazyBInput: LazyComponent<typeof import("bootstrap-vue-next/components/BFormInput").BInput>
export const LazyBInputGroup: LazyComponent<typeof import("bootstrap-vue-next/components/BInputGroup").BInputGroup>
export const LazyBInputGroupText: LazyComponent<typeof import("bootstrap-vue-next/components/BInputGroup").BInputGroupText>
export const LazyBListGroup: LazyComponent<typeof import("bootstrap-vue-next/components/BListGroup").BListGroup>
export const LazyBListGroupItem: LazyComponent<typeof import("bootstrap-vue-next/components/BListGroup").BListGroupItem>
export const LazyBModal: LazyComponent<typeof import("bootstrap-vue-next/components/BModal").BModal>
export const LazyBModalOrchestrator: LazyComponent<typeof import("bootstrap-vue-next/components/BModal").BModalOrchestrator>
export const LazyBNav: LazyComponent<typeof import("bootstrap-vue-next/components/BNav").BNav>
export const LazyBNavForm: LazyComponent<typeof import("bootstrap-vue-next/components/BNav").BNavForm>
export const LazyBNavItem: LazyComponent<typeof import("bootstrap-vue-next/components/BNav").BNavItem>
export const LazyBNavItemDropdown: LazyComponent<typeof import("bootstrap-vue-next/components/BNav").BNavItemDropdown>
export const LazyBNavText: LazyComponent<typeof import("bootstrap-vue-next/components/BNav").BNavText>
export const LazyBNavbar: LazyComponent<typeof import("bootstrap-vue-next/components/BNavbar").BNavbar>
export const LazyBNavbarBrand: LazyComponent<typeof import("bootstrap-vue-next/components/BNavbar").BNavbarBrand>
export const LazyBNavbarNav: LazyComponent<typeof import("bootstrap-vue-next/components/BNavbar").BNavbarNav>
export const LazyBNavbarToggle: LazyComponent<typeof import("bootstrap-vue-next/components/BNavbar").BNavbarToggle>
export const LazyBOffcanvas: LazyComponent<typeof import("bootstrap-vue-next/components/BOffcanvas").BOffcanvas>
export const LazyBOverlay: LazyComponent<typeof import("bootstrap-vue-next/components/BOverlay").BOverlay>
export const LazyBPagination: LazyComponent<typeof import("bootstrap-vue-next/components/BPagination").BPagination>
export const LazyBPlaceholder: LazyComponent<typeof import("bootstrap-vue-next/components/BPlaceholder").BPlaceholder>
export const LazyBPlaceholderButton: LazyComponent<typeof import("bootstrap-vue-next/components/BPlaceholder").BPlaceholderButton>
export const LazyBPlaceholderCard: LazyComponent<typeof import("bootstrap-vue-next/components/BPlaceholder").BPlaceholderCard>
export const LazyBPlaceholderTable: LazyComponent<typeof import("bootstrap-vue-next/components/BPlaceholder").BPlaceholderTable>
export const LazyBPlaceholderWrapper: LazyComponent<typeof import("bootstrap-vue-next/components/BPlaceholder").BPlaceholderWrapper>
export const LazyBPopover: LazyComponent<typeof import("bootstrap-vue-next/components/BPopover").BPopover>
export const LazyBProgress: LazyComponent<typeof import("bootstrap-vue-next/components/BProgress").BProgress>
export const LazyBRow: LazyComponent<typeof import("bootstrap-vue-next/components/BContainer").BRow>
export const LazyBSpinner: LazyComponent<typeof import("bootstrap-vue-next/components/BSpinner").BSpinner>
export const LazyBTab: LazyComponent<typeof import("bootstrap-vue-next/components/BTabs").BTab>
export const LazyBTabs: LazyComponent<typeof import("bootstrap-vue-next/components/BTabs").BTabs>
export const LazyBToast: LazyComponent<typeof import("bootstrap-vue-next/components/BToast").BToast>
export const LazyBToastOrchestrator: LazyComponent<typeof import("bootstrap-vue-next/components/BToast").BToastOrchestrator>
export const LazyBTooltip: LazyComponent<typeof import("bootstrap-vue-next/components/BTooltip").BTooltip>
export const LazyBLink: LazyComponent<typeof import("bootstrap-vue-next/components/BLink").BLink>
export const LazyBProgressBar: LazyComponent<typeof import("bootstrap-vue-next/components/BProgress").BProgressBar>
export const LazyBTableSimple: LazyComponent<typeof import("bootstrap-vue-next/components/BTable").BTableSimple>
export const LazyBTableLite: LazyComponent<typeof import("bootstrap-vue-next/components/BTable").BTableLite>
export const LazyBTable: LazyComponent<typeof import("bootstrap-vue-next/components/BTable").BTable>
export const LazyBTbody: LazyComponent<typeof import("bootstrap-vue-next/components/BTable").BTbody>
export const LazyBTd: LazyComponent<typeof import("bootstrap-vue-next/components/BTable").BTd>
export const LazyBTh: LazyComponent<typeof import("bootstrap-vue-next/components/BTable").BTh>
export const LazyBThead: LazyComponent<typeof import("bootstrap-vue-next/components/BTable").BThead>
export const LazyBTfoot: LazyComponent<typeof import("bootstrap-vue-next/components/BTable").BTfoot>
export const LazyBTr: LazyComponent<typeof import("bootstrap-vue-next/components/BTable").BTr>
export const LazyBPopoverOrchestrator: LazyComponent<typeof import("bootstrap-vue-next/components/BPopover").BPopoverOrchestrator>
export const LazyNuxtLinkLocale: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+i18n@10.2.1_@vue+compiler-dom@3.5.27_db0@0.3.4_eslint@9.39.2_jiti@2.6.1__idb-ke_d844bff0289b9fea1b2ee74a046c285f/node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale").default>
export const LazySwitchLocalePathLink: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+i18n@10.2.1_@vue+compiler-dom@3.5.27_db0@0.3.4_eslint@9.39.2_jiti@2.6.1__idb-ke_d844bff0289b9fea1b2ee74a046c285f/node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink").default>
export const LazyVitePwaManifest: LazyComponent<typeof import("../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.0_magicast@0.5.1_vite@7.3.1_@types+node@24.10.9_jiti@2.6.1_sass-embe_3c67240a609a9e48fa8175d737b11896/node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest").default>
export const LazyNuxtPwaManifest: LazyComponent<typeof import("../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.0_magicast@0.5.1_vite@7.3.1_@types+node@24.10.9_jiti@2.6.1_sass-embe_3c67240a609a9e48fa8175d737b11896/node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest").default>
export const LazyNuxtPwaAssets: LazyComponent<typeof import("../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.0_magicast@0.5.1_vite@7.3.1_@types+node@24.10.9_jiti@2.6.1_sass-embe_3c67240a609a9e48fa8175d737b11896/node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets").default>
export const LazyPwaAppleImage: LazyComponent<typeof import("../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.0_magicast@0.5.1_vite@7.3.1_@types+node@24.10.9_jiti@2.6.1_sass-embe_3c67240a609a9e48fa8175d737b11896/node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaAppleImage").default>
export const LazyPwaAppleSplashScreenImage: LazyComponent<typeof import("../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.0_magicast@0.5.1_vite@7.3.1_@types+node@24.10.9_jiti@2.6.1_sass-embe_3c67240a609a9e48fa8175d737b11896/node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaAppleSplashScreenImage").default>
export const LazyPwaFaviconImage: LazyComponent<typeof import("../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.0_magicast@0.5.1_vite@7.3.1_@types+node@24.10.9_jiti@2.6.1_sass-embe_3c67240a609a9e48fa8175d737b11896/node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaFaviconImage").default>
export const LazyPwaMaskableImage: LazyComponent<typeof import("../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.0_magicast@0.5.1_vite@7.3.1_@types+node@24.10.9_jiti@2.6.1_sass-embe_3c67240a609a9e48fa8175d737b11896/node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaMaskableImage").default>
export const LazyPwaTransparentImage: LazyComponent<typeof import("../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.0_magicast@0.5.1_vite@7.3.1_@types+node@24.10.9_jiti@2.6.1_sass-embe_3c67240a609a9e48fa8175d737b11896/node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaTransparentImage").default>
export const LazyNuxtPage: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/pages/runtime/page").default>
export const LazyNoScript: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/head/runtime/components").NoScript>
export const LazyLink: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/head/runtime/components").Link>
export const LazyBase: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/head/runtime/components").Base>
export const LazyTitle: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/head/runtime/components").Title>
export const LazyMeta: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/head/runtime/components").Meta>
export const LazyStyle: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/head/runtime/components").Style>
export const LazyHead: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/head/runtime/components").Head>
export const LazyHtml: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/head/runtime/components").Html>
export const LazyBody: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/head/runtime/components").Body>
export const LazyNuxtIsland: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/nuxt-island").default>

export const componentNames: string[]
