[package]
name = "tests"
version = "0.1.0"
edition = { workspace = true }

[lib]
crate-type = ["rlib", "cdylib"]
doctest = false

[dependencies]
arbitrary = { version = "1", features = ["derive"] }
sep-40-oracle = { workspace = true, features = ["testutils"] }
soroban-fixed-point-math = { workspace = true }
soroban-sdk = { workspace = true, features = ["testutils"] }

[dependencies.market]
path = "../contracts/market"
features = ["testutils"]

[dependencies.market-manager]
path = "../contracts/market-manager"
