[package]
name = "lending-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
extension-trait = "1"
libfuzzer-sys = "0.4"
soroban-fixed-point-math = "1.3.0"
soroban-sdk = { version = "22.0.8", features = ["testutils"] }

[dependencies.lending]
path = "../../contracts/lending"
features = ["testutils"]

[dependencies.tests]
path = ".."

[[bin]]
name = "fuzz_target"
path = "fuzz_targets/fuzz_target.rs"
test = false
doc = false
bench = false
