[package]
name = "aggregated_oracle"
version = "0.0.1"
edition = { workspace = true }
description = "A Soroban smart contract that aggregates data from multiple SEP-40 oracles."
publish = false

[lib]
crate-type = ["lib", "cdylib"]
doctest = false

[dependencies]
sep-40-oracle = { workspace = true }
soroban-fixed-point-math = { workspace = true }
soroban-sdk = { workspace = true }

[dev-dependencies]
sep-40-oracle = { workspace = true }
soroban-sdk = { workspace = true, features = ["testutils"] }

[features]
mainnet = []
