pub const REDSTONE_DECIMALS: u32 = 8;
pub const REDSTONE_TS_PER_SEC: u64 = 1_000;

pub const MIN_RESOLUTION: u32 = 60; // 60 seconds
pub const MAX_RESOLUTION: u32 = 25 * 60 * 60; // 25 hours

// -- TTL extension --

pub const SECONDS_PER_LEDGER: u32 = 6;
pub const SECONDS_PER_DAY: u32 = 24 * 60 * 60;
pub const LEDGERS_PER_DAY: u32 = SECONDS_PER_DAY / SECONDS_PER_LEDGER;

pub const INSTANCE_THRESHOLD: u32 = 40 * LEDGERS_PER_DAY;
pub const INSTANCE_BUMP: u32 = INSTANCE_THRESHOLD + LEDGERS_PER_DAY;

pub const PERSISTENT_THRESHOLD: u32 = 40 * LEDGERS_PER_DAY;
pub const PERSISTENT_BUMP: u32 = PERSISTENT_THRESHOLD + LEDGERS_PER_DAY;
