[package]
name = "flash-loan-taker-mock"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["lib", "cdylib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
moderc3156 = { workspace = true }
lending = { path = "../lending" }

[dev-dependencies]
tests = { path = "../../tests" }