[package]
name = "flash-loan-taker-mock"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
crate-type = ["lib", "cdylib"]
doctest = false

[dependencies]
market = { path = "../market" }
moderc3156 = { workspace = true }
soroban-sdk = { workspace = true }

[dev-dependencies]
tests = { path = "../../tests" }
