use soroban_sdk::contracterror;

#[contracterror]
#[derive(Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum LendingContractError {
    InternalError = 0,
    PoolAlreadyExists = 1,
    PoolDoesNotExist = 2,
    InvalidLoanPoolConfig = 3,
    NotEnoughPoolFunds = 4,
    ObligationDoesNotExist = 5,
    DepositDoesNotExist = 6,
    NegativeDeposit = 7,
    NegativeWithdraw = 8,
    WithdrawOverBalance = 9,
    NegativeRepay = 10,
    OverOrUnderflow = 11,
    OracleDoesNotKnowAssetPrice = 12,
    BorrowDoesNotExist = 13,
    HealthFactorIsLowerThanRequiredThreshold = 14,
    InvalidLiquidationThreshold = 15,
    LiquidatedPositionIsHealthy = 16,
    LiquidationExceedsCloseFactor = 17,
    NegativeLiquidation = 18,
    NegativeBorrow = 19,
    CollateralPoolDoesNotExist = 20,
    NegativeFlashLoan = 21,
    InvalidTimestamp = 23,
    SelfLiquidation = 24,
    DepositPoolDoesNotExist = 27,
    BorrowPoolDoesNotExist = 28,
    InvalidLeverageMultiplier = 29,
    InvalidSwapSlippage = 30,
    DependencyContractError = 31,
    SupplyLimitExceeded = 32,
    BorrowLimitExceeded = 33,
    NegativeCollateralAddition = 34,
    NegativeCollateralRemoval = 35,
    LiquidationWithEqualCollateralAndDepositPools = 36,
}
