[package]
name = "redstone_sep_40_adapter"
version = "0.0.1"
edition = { workspace = true }
license = { workspace = true }
description = "A Soroban smart contract that adapts RedStone oracle feeds to the SEP-40 interface."
publish = false

[lib]
crate-type = ["lib", "cdylib"]
doctest = false

[dependencies]
sep-40-oracle = { workspace = true }
soroban-sdk = { workspace = true }
