[package]
name = "soroswap_sep_40_adapter"
version = "0.0.1"
edition = { workspace = true }
license = { workspace = true }
description = "A Soroban smart contract that aggregates data from multiple SEP-40 oracles."
publish = false

[lib]
crate-type = ["lib", "cdylib"]
doctest = false

[dependencies]
sep-40-oracle = { workspace = true }
soroban-sdk = { workspace = true }

[features]
mainnet = []
