
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  'AccountPage': typeof import("../../src/components/AccountsPage/AccountPage.vue").default
  'RepayDialog': typeof import("../../src/components/AccountsPage/Dialogs/RepayDialog.vue").default
  'WithdrawDialog': typeof import("../../src/components/AccountsPage/Dialogs/WithdrawDialog.vue").default
  'AccountBorrowTable': typeof import("../../src/components/AccountsPage/Tables/AccountBorrowTable.vue").default
  'AccountBorrowTableMobile': typeof import("../../src/components/AccountsPage/Tables/AccountBorrowTableMobile.vue").default
  'AccountMultiplyTable': typeof import("../../src/components/AccountsPage/Tables/AccountMultiplyTable.vue").default
  'AccountSupplyTable': typeof import("../../src/components/AccountsPage/Tables/AccountSupplyTable.vue").default
  'AccountSupplyTableMobile': typeof import("../../src/components/AccountsPage/Tables/AccountSupplyTableMobile.vue").default
  'AppFooter': typeof import("../../src/components/AppFooter.vue").default
  'AppHeader': typeof import("../../src/components/AppHeader.vue").default
  'JAccordion': typeof import("../../src/components/Common/JAccordion.vue").default
  'JBtn': typeof import("../../src/components/Common/JBtn.vue").default
  'JBtnGroup': typeof import("../../src/components/Common/JBtnGroup.vue").default
  'JCheckbox': typeof import("../../src/components/Common/JCheckbox.vue").default
  'JCircularProgress': typeof import("../../src/components/Common/JCircularProgress.vue").default
  'JDialog': typeof import("../../src/components/Common/JDialog.vue").default
  'JDropdown': typeof import("../../src/components/Common/JDropdown.vue").default
  'JInput': typeof import("../../src/components/Common/JInput.vue").default
  'JLineTab': typeof import("../../src/components/Common/JLineTab.vue").default
  'JLoadingSpinner': typeof import("../../src/components/Common/JLoadingSpinner.vue").default
  'JPillLabel': typeof import("../../src/components/Common/JPillLabel.vue").default
  'JPopover': typeof import("../../src/components/Common/JPopover.vue").default
  'JSelect': typeof import("../../src/components/Common/JSelect.vue").default
  'JSelectPopover': typeof import("../../src/components/Common/JSelectPopover.vue").default
  'JSkeleton': typeof import("../../src/components/Common/JSkeleton.vue").default
  'JToggle': typeof import("../../src/components/Common/JToggle.vue").default
  'JTooltip': typeof import("../../src/components/Common/JTooltip.vue").default
  'ConnectWallet': typeof import("../../src/components/ConnectWallet.vue").default
  'CopyToClipboard': typeof import("../../src/components/CopyToClipboard.vue").default
  'CustomMixedChart': typeof import("../../src/components/CustomMixedChart.vue").default
  'DynamicTeleport': typeof import("../../src/components/DynamicTeleport.vue").default
  'FaucetMenu': typeof import("../../src/components/FaucetMenu.vue").default
  'BorrowDialog': typeof import("../../src/components/MarketsPage/Markets/Dialogs/BorrowDialog.vue").default
  'SupplyDialog': typeof import("../../src/components/MarketsPage/Markets/Dialogs/SupplyDialog.vue").default
  'ClearFiltersBtn': typeof import("../../src/components/MarketsPage/Markets/Filters/ClearFiltersBtn.vue").default
  'CollapseAllBtn': typeof import("../../src/components/MarketsPage/Markets/Filters/CollapseAllBtn.vue").default
  'CollateralAssetsFilter': typeof import("../../src/components/MarketsPage/Markets/Filters/CollateralAssetsFilter.vue").default
  'DebtAssetsFilter': typeof import("../../src/components/MarketsPage/Markets/Filters/DebtAssetsFilter.vue").default
  'MarketSearch': typeof import("../../src/components/MarketsPage/Markets/Filters/MarketSearch.vue").default
  'MarketProgress': typeof import("../../src/components/MarketsPage/Markets/MarketDetailInfo/MarketProgress.vue").default
  'Markets': typeof import("../../src/components/MarketsPage/Markets/Markets.vue").default
  'MyPositionsWidget': typeof import("../../src/components/MarketsPage/Markets/MyPositionsWidget.vue").default
  'MarketsList': typeof import("../../src/components/MarketsPage/Markets/Tables/MarketsList.vue").default
  'MarketsListMobile': typeof import("../../src/components/MarketsPage/Markets/Tables/MarketsListMobile.vue").default
  'MarketsInfo': typeof import("../../src/components/MarketsPage/MarketsInfo.vue").default
  'MarketsPage': typeof import("../../src/components/MarketsPage/MarketsPage.vue").default
  'MultiplyDetailTop': typeof import("../../src/components/MultiplyDetailsPage/MultiplyDetailTop.vue").default
  'MultiplyDetailsPage': typeof import("../../src/components/MultiplyDetailsPage/MultiplyDetailsPage.vue").default
  'MultiplyOverview': typeof import("../../src/components/MultiplyDetailsPage/Overview/MultiplyOverview.vue").default
  'MultiplyForm': typeof import("../../src/components/MultiplyDetailsPage/Overview/Sections/MultiplyForm.vue").default
  'MultiplyHistoryChart': typeof import("../../src/components/MultiplyDetailsPage/Overview/Sections/MultiplyHistoryChart.vue").default
  'MultiplyStats': typeof import("../../src/components/MultiplyDetailsPage/Overview/Sections/MultiplyStats.vue").default
  'MultiplyVault': typeof import("../../src/components/MultiplyDetailsPage/Overview/Sections/MultiplyVault.vue").default
  'MultiplyPosition': typeof import("../../src/components/MultiplyDetailsPage/Position/MultiplyPosition.vue").default
  'RiskWarning': typeof import("../../src/components/MultiplyDetailsPage/Position/RiskWarning.vue").default
  'MyMultiplyPositions': typeof import("../../src/components/MultiplyDetailsPage/Position/Sections/MyMultiplyPositions.vue").default
  'MultiplyDialog': typeof import("../../src/components/MultiplyPage/Dialogs/MultiplyDialog.vue").default
  'WithdrawLeverageDialog': typeof import("../../src/components/MultiplyPage/Dialogs/WithdrawLeverageDialog.vue").default
  'MultiplyApyChart': typeof import("../../src/components/MultiplyPage/MultiplyApyChart.vue").default
  'MultiplyPage': typeof import("../../src/components/MultiplyPage/MultiplyPage.vue").default
  'MultiplySelect': typeof import("../../src/components/MultiplyPage/MultiplySelect.vue").default
  'MultiplyTable': typeof import("../../src/components/MultiplyPage/Tables/MultiplyTable.vue").default
  'MultiplyTableMobile': typeof import("../../src/components/MultiplyPage/Tables/MultiplyTableMobile.vue").default
  'PoolHistoryChart': typeof import("../../src/components/PoolDetailPage/Charts/PoolHistoryChart.vue").default
  'PoolInterestChart': typeof import("../../src/components/PoolDetailPage/Charts/PoolInterestChart.vue").default
  'PoolOverview': typeof import("../../src/components/PoolDetailPage/Overview/PoolOverview.vue").default
  'PoolOverviewBottomTabs': typeof import("../../src/components/PoolDetailPage/Overview/PoolOverviewBottomTabs.vue").default
  'PoolDetailOverview': typeof import("../../src/components/PoolDetailPage/Overview/Sections/PoolDetailOverview.vue").default
  'PoolInfoOverview': typeof import("../../src/components/PoolDetailPage/Overview/Sections/PoolInfoOverview.vue").default
  'PoolSupplyBorrowOverview': typeof import("../../src/components/PoolDetailPage/Overview/Sections/PoolSupplyBorrowOverview.vue").default
  'BorrowOverview': typeof import("../../src/components/PoolDetailPage/Overview/Sections/SupplyBorrow/BorrowOverview.vue").default
  'SupplyOverview': typeof import("../../src/components/PoolDetailPage/Overview/Sections/SupplyBorrow/SupplyOverview.vue").default
  'PoolDetailPage': typeof import("../../src/components/PoolDetailPage/PoolDetailPage.vue").default
  'PoolDetailTop': typeof import("../../src/components/PoolDetailPage/PoolDetailTop.vue").default
  'PoolInfoRisks': typeof import("../../src/components/PoolDetailPage/PoolInfoRisks.vue").default
  'MyPosition': typeof import("../../src/components/PoolDetailPage/Position/MyPosition.vue").default
  'PositionBorrowLimits': typeof import("../../src/components/PoolDetailPage/Position/PositionBorrowLimits.vue").default
  'PositionOverview': typeof import("../../src/components/PoolDetailPage/Position/PositionOverview.vue").default
  'PositionRiskMetrics': typeof import("../../src/components/PoolDetailPage/Position/PositionRiskMetrics.vue").default
  'PositionSupplyInfo': typeof import("../../src/components/PoolDetailPage/Position/PositionSupplyInfo.vue").default
  'AppSettings': typeof import("../../src/components/Settings/AppSettings.vue").default
  'SettingsConnect': typeof import("../../src/components/Settings/Options/SettingsConnect.vue").default
  'SettingsLanguage': typeof import("../../src/components/Settings/Options/SettingsLanguage.vue").default
  'SettingsNavigation': typeof import("../../src/components/Settings/Options/SettingsNavigation.vue").default
  'SettingsNetwork': typeof import("../../src/components/Settings/Options/SettingsNetwork.vue").default
  'SettingsRecentActivity': typeof import("../../src/components/Settings/Options/SettingsRecentActivity.vue").default
  'SettingsTheme': typeof import("../../src/components/Settings/Options/SettingsTheme.vue").default
  'SettingsSidebar': typeof import("../../src/components/Settings/SettingsSidebar.vue").default
  'Sidebar': typeof import("../../src/components/Sidebar/Sidebar.vue").default
  'SidebarPanel': typeof import("../../src/components/Sidebar/SidebarPanel.vue").default
  'BorrowTableSkeleton': typeof import("../../src/components/Skeleton/BorrowTableSkeleton.vue").default
  'MarketInfoSkeleton': typeof import("../../src/components/Skeleton/MarketInfoSkeleton.vue").default
  'MarketTableSkeleton': typeof import("../../src/components/Skeleton/MarketTableSkeleton.vue").default
  'MarketTableSkeletonMobile': typeof import("../../src/components/Skeleton/MarketTableSkeletonMobile.vue").default
  'PoolDetailSkeleton': typeof import("../../src/components/Skeleton/PoolDetailSkeleton.vue").default
  'SupplyTableSkeleton': typeof import("../../src/components/Skeleton/SupplyTableSkeleton.vue").default
  'TableSkeletonMobile': typeof import("../../src/components/Skeleton/TableSkeletonMobile.vue").default
  'BorrowWindow': typeof import("../../src/components/SupplyCard/BorrowWindow.vue").default
  'ChangePoolDialog': typeof import("../../src/components/SupplyCard/ChangePoolDialog.vue").default
  'RepayWindow': typeof import("../../src/components/SupplyCard/RepayWindow.vue").default
  'SupplyCard': typeof import("../../src/components/SupplyCard/SupplyCard.vue").default
  'SupplyWindow': typeof import("../../src/components/SupplyCard/SupplyWindow.vue").default
  'WithdrawWindow': typeof import("../../src/components/SupplyCard/WithdrawWindow.vue").default
  'AddressIcon': typeof import("../../src/components/Widget/AddressIcon.vue").default
  'BackBtn': typeof import("../../src/components/Widget/BackBtn.vue").default
  'ChartDateFilter': typeof import("../../src/components/Widget/ChartDateFilter.vue").default
  'InfoPanel': typeof import("../../src/components/Widget/InfoPanel.vue").default
  'InfoTooltip': typeof import("../../src/components/Widget/InfoTooltip.vue").default
  'InputWidget': typeof import("../../src/components/Widget/InputWidget.vue").default
  'LightingApy': typeof import("../../src/components/Widget/LightingApy.vue").default
  'LogoWithText': typeof import("../../src/components/Widget/LogoWithText.vue").default
  'MarketDialogActionBtn': typeof import("../../src/components/Widget/MarketDialogActionBtn.vue").default
  'MarketInfoBadge': typeof import("../../src/components/Widget/MarketInfoBadge.vue").default
  'MarketInfoDetailCard': typeof import("../../src/components/Widget/MarketInfoDetailCard.vue").default
  'MetricIndicator': typeof import("../../src/components/Widget/MetricIndicator.vue").default
  'PoolStatus': typeof import("../../src/components/Widget/PoolStatus.vue").default
  'ReloadCoundown': typeof import("../../src/components/Widget/ReloadCoundown.vue").default
  'TableMobileCard': typeof import("../../src/components/Widget/TableMobileCard.vue").default
  'TotalCard': typeof import("../../src/components/Widget/TotalCard.vue").default
  'WarningBlock': typeof import("../../src/components/Widget/WarningBlock.vue").default
  'NuxtWelcome': typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/welcome.vue").default
  'NuxtLayout': typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/nuxt-layout").default
  'NuxtErrorBoundary': typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default
  'ClientOnly': typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/client-only").default
  'DevOnly': typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/dev-only").default
  'ServerPlaceholder': typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/server-placeholder").default
  'NuxtLink': typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/nuxt-link").default
  'NuxtLoadingIndicator': typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default
  'NuxtTime': typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/nuxt-time.vue").default
  'NuxtRouteAnnouncer': typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/nuxt-route-announcer").default
  'NuxtImg': typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtImg
  'NuxtPicture': typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtPicture
  'BAccordion': typeof import("bootstrap-vue-next/components/BAccordion").BAccordion
  'BAccordionItem': typeof import("bootstrap-vue-next/components/BAccordion").BAccordionItem
  'BAlert': typeof import("bootstrap-vue-next/components/BAlert").BAlert
  'BAvatar': typeof import("bootstrap-vue-next/components/BAvatar").BAvatar
  'BAvatarGroup': typeof import("bootstrap-vue-next/components/BAvatar").BAvatarGroup
  'BBadge': typeof import("bootstrap-vue-next/components/BBadge").BBadge
  'BBreadcrumb': typeof import("bootstrap-vue-next/components/BBreadcrumb").BBreadcrumb
  'BBreadcrumbItem': typeof import("bootstrap-vue-next/components/BBreadcrumb").BBreadcrumbItem
  'BButton': typeof import("bootstrap-vue-next/components/BButton").BButton
  'BButtonGroup': typeof import("bootstrap-vue-next/components/BButton").BButtonGroup
  'BButtonToolbar': typeof import("bootstrap-vue-next/components/BButton").BButtonToolbar
  'BCloseButton': typeof import("bootstrap-vue-next/components/BButton").BCloseButton
  'BCard': typeof import("bootstrap-vue-next/components/BCard").BCard
  'BCardBody': typeof import("bootstrap-vue-next/components/BCard").BCardBody
  'BCardFooter': typeof import("bootstrap-vue-next/components/BCard").BCardFooter
  'BCardGroup': typeof import("bootstrap-vue-next/components/BCard").BCardGroup
  'BCardHeader': typeof import("bootstrap-vue-next/components/BCard").BCardHeader
  'BCardImg': typeof import("bootstrap-vue-next/components/BCard").BCardImg
  'BCardSubtitle': typeof import("bootstrap-vue-next/components/BCard").BCardSubtitle
  'BCardText': typeof import("bootstrap-vue-next/components/BCard").BCardText
  'BCardTitle': typeof import("bootstrap-vue-next/components/BCard").BCardTitle
  'BCarousel': typeof import("bootstrap-vue-next/components/BCarousel").BCarousel
  'BCarouselSlide': typeof import("bootstrap-vue-next/components/BCarousel").BCarouselSlide
  'BCol': typeof import("bootstrap-vue-next/components/BContainer").BCol
  'BCollapse': typeof import("bootstrap-vue-next/components/BCollapse").BCollapse
  'BContainer': typeof import("bootstrap-vue-next/components/BContainer").BContainer
  'BDropdown': typeof import("bootstrap-vue-next/components/BDropdown").BDropdown
  'BDropdownDivider': typeof import("bootstrap-vue-next/components/BDropdown").BDropdownDivider
  'BDropdownForm': typeof import("bootstrap-vue-next/components/BDropdown").BDropdownForm
  'BDropdownGroup': typeof import("bootstrap-vue-next/components/BDropdown").BDropdownGroup
  'BDropdownHeader': typeof import("bootstrap-vue-next/components/BDropdown").BDropdownHeader
  'BDropdownItem': typeof import("bootstrap-vue-next/components/BDropdown").BDropdownItem
  'BDropdownItemButton': typeof import("bootstrap-vue-next/components/BDropdown").BDropdownItemButton
  'BDropdownText': typeof import("bootstrap-vue-next/components/BDropdown").BDropdownText
  'BForm': typeof import("bootstrap-vue-next/components/BForm").BForm
  'BFormCheckbox': typeof import("bootstrap-vue-next/components/BFormCheckbox").BFormCheckbox
  'BFormCheckboxGroup': typeof import("bootstrap-vue-next/components/BFormCheckbox").BFormCheckboxGroup
  'BFormDatalist': typeof import("bootstrap-vue-next/components/BForm").BFormDatalist
  'BFormFile': typeof import("bootstrap-vue-next/components/BFormFile").BFormFile
  'BFormFloatingLabel': typeof import("bootstrap-vue-next/components/BForm").BFormFloatingLabel
  'BFormGroup': typeof import("bootstrap-vue-next/components/BFormGroup").BFormGroup
  'BFormInput': typeof import("bootstrap-vue-next/components/BFormInput").BFormInput
  'BFormInvalidFeedback': typeof import("bootstrap-vue-next/components/BForm").BFormInvalidFeedback
  'BFormRadio': typeof import("bootstrap-vue-next/components/BFormRadio").BFormRadio
  'BFormRadioGroup': typeof import("bootstrap-vue-next/components/BFormRadio").BFormRadioGroup
  'BFormRating': typeof import("bootstrap-vue-next/components/BFormRating").BFormRating
  'BFormRow': typeof import("bootstrap-vue-next/components/BForm").BFormRow
  'BFormSelect': typeof import("bootstrap-vue-next/components/BFormSelect").BFormSelect
  'BFormSelectOption': typeof import("bootstrap-vue-next/components/BFormSelect").BFormSelectOption
  'BFormSelectOptionGroup': typeof import("bootstrap-vue-next/components/BFormSelect").BFormSelectOptionGroup
  'BFormSpinbutton': typeof import("bootstrap-vue-next/components/BFormSpinbutton").BFormSpinbutton
  'BFormTag': typeof import("bootstrap-vue-next/components/BFormTags").BFormTag
  'BFormTags': typeof import("bootstrap-vue-next/components/BFormTags").BFormTags
  'BFormText': typeof import("bootstrap-vue-next/components/BForm").BFormText
  'BFormTextarea': typeof import("bootstrap-vue-next/components/BFormTextarea").BFormTextarea
  'BFormValidFeedback': typeof import("bootstrap-vue-next/components/BForm").BFormValidFeedback
  'BImg': typeof import("bootstrap-vue-next/components/BImg").BImg
  'BInput': typeof import("bootstrap-vue-next/components/BFormInput").BInput
  'BInputGroup': typeof import("bootstrap-vue-next/components/BInputGroup").BInputGroup
  'BInputGroupText': typeof import("bootstrap-vue-next/components/BInputGroup").BInputGroupText
  'BListGroup': typeof import("bootstrap-vue-next/components/BListGroup").BListGroup
  'BListGroupItem': typeof import("bootstrap-vue-next/components/BListGroup").BListGroupItem
  'BModal': typeof import("bootstrap-vue-next/components/BModal").BModal
  'BModalOrchestrator': typeof import("bootstrap-vue-next/components/BModal").BModalOrchestrator
  'BNav': typeof import("bootstrap-vue-next/components/BNav").BNav
  'BNavForm': typeof import("bootstrap-vue-next/components/BNav").BNavForm
  'BNavItem': typeof import("bootstrap-vue-next/components/BNav").BNavItem
  'BNavItemDropdown': typeof import("bootstrap-vue-next/components/BNav").BNavItemDropdown
  'BNavText': typeof import("bootstrap-vue-next/components/BNav").BNavText
  'BNavbar': typeof import("bootstrap-vue-next/components/BNavbar").BNavbar
  'BNavbarBrand': typeof import("bootstrap-vue-next/components/BNavbar").BNavbarBrand
  'BNavbarNav': typeof import("bootstrap-vue-next/components/BNavbar").BNavbarNav
  'BNavbarToggle': typeof import("bootstrap-vue-next/components/BNavbar").BNavbarToggle
  'BOffcanvas': typeof import("bootstrap-vue-next/components/BOffcanvas").BOffcanvas
  'BOverlay': typeof import("bootstrap-vue-next/components/BOverlay").BOverlay
  'BPagination': typeof import("bootstrap-vue-next/components/BPagination").BPagination
  'BPlaceholder': typeof import("bootstrap-vue-next/components/BPlaceholder").BPlaceholder
  'BPlaceholderButton': typeof import("bootstrap-vue-next/components/BPlaceholder").BPlaceholderButton
  'BPlaceholderCard': typeof import("bootstrap-vue-next/components/BPlaceholder").BPlaceholderCard
  'BPlaceholderTable': typeof import("bootstrap-vue-next/components/BPlaceholder").BPlaceholderTable
  'BPlaceholderWrapper': typeof import("bootstrap-vue-next/components/BPlaceholder").BPlaceholderWrapper
  'BPopover': typeof import("bootstrap-vue-next/components/BPopover").BPopover
  'BProgress': typeof import("bootstrap-vue-next/components/BProgress").BProgress
  'BRow': typeof import("bootstrap-vue-next/components/BContainer").BRow
  'BSpinner': typeof import("bootstrap-vue-next/components/BSpinner").BSpinner
  'BTab': typeof import("bootstrap-vue-next/components/BTabs").BTab
  'BTabs': typeof import("bootstrap-vue-next/components/BTabs").BTabs
  'BToast': typeof import("bootstrap-vue-next/components/BToast").BToast
  'BToastOrchestrator': typeof import("bootstrap-vue-next/components/BToast").BToastOrchestrator
  'BTooltip': typeof import("bootstrap-vue-next/components/BTooltip").BTooltip
  'BLink': typeof import("bootstrap-vue-next/components/BLink").BLink
  'BProgressBar': typeof import("bootstrap-vue-next/components/BProgress").BProgressBar
  'BTableSimple': typeof import("bootstrap-vue-next/components/BTable").BTableSimple
  'BTableLite': typeof import("bootstrap-vue-next/components/BTable").BTableLite
  'BTable': typeof import("bootstrap-vue-next/components/BTable").BTable
  'BTbody': typeof import("bootstrap-vue-next/components/BTable").BTbody
  'BTd': typeof import("bootstrap-vue-next/components/BTable").BTd
  'BTh': typeof import("bootstrap-vue-next/components/BTable").BTh
  'BThead': typeof import("bootstrap-vue-next/components/BTable").BThead
  'BTfoot': typeof import("bootstrap-vue-next/components/BTable").BTfoot
  'BTr': typeof import("bootstrap-vue-next/components/BTable").BTr
  'BPopoverOrchestrator': typeof import("bootstrap-vue-next/components/BPopover").BPopoverOrchestrator
  'NuxtLinkLocale': typeof import("../../../../node_modules/.pnpm/@nuxtjs+i18n@10.2.1_@vue+compiler-dom@3.5.27_db0@0.3.4_eslint@9.39.2_jiti@2.6.1__idb-ke_d844bff0289b9fea1b2ee74a046c285f/node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale").default
  'SwitchLocalePathLink': typeof import("../../../../node_modules/.pnpm/@nuxtjs+i18n@10.2.1_@vue+compiler-dom@3.5.27_db0@0.3.4_eslint@9.39.2_jiti@2.6.1__idb-ke_d844bff0289b9fea1b2ee74a046c285f/node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink").default
  'VitePwaManifest': typeof import("../../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.0_magicast@0.5.1_vite@7.3.1_@types+node@24.10.9_jiti@2.6.1_sass-embe_3c67240a609a9e48fa8175d737b11896/node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest").default
  'NuxtPwaManifest': typeof import("../../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.0_magicast@0.5.1_vite@7.3.1_@types+node@24.10.9_jiti@2.6.1_sass-embe_3c67240a609a9e48fa8175d737b11896/node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest").default
  'NuxtPwaAssets': typeof import("../../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.0_magicast@0.5.1_vite@7.3.1_@types+node@24.10.9_jiti@2.6.1_sass-embe_3c67240a609a9e48fa8175d737b11896/node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets").default
  'PwaAppleImage': typeof import("../../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.0_magicast@0.5.1_vite@7.3.1_@types+node@24.10.9_jiti@2.6.1_sass-embe_3c67240a609a9e48fa8175d737b11896/node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaAppleImage").default
  'PwaAppleSplashScreenImage': typeof import("../../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.0_magicast@0.5.1_vite@7.3.1_@types+node@24.10.9_jiti@2.6.1_sass-embe_3c67240a609a9e48fa8175d737b11896/node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaAppleSplashScreenImage").default
  'PwaFaviconImage': typeof import("../../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.0_magicast@0.5.1_vite@7.3.1_@types+node@24.10.9_jiti@2.6.1_sass-embe_3c67240a609a9e48fa8175d737b11896/node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaFaviconImage").default
  'PwaMaskableImage': typeof import("../../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.0_magicast@0.5.1_vite@7.3.1_@types+node@24.10.9_jiti@2.6.1_sass-embe_3c67240a609a9e48fa8175d737b11896/node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaMaskableImage").default
  'PwaTransparentImage': typeof import("../../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.0_magicast@0.5.1_vite@7.3.1_@types+node@24.10.9_jiti@2.6.1_sass-embe_3c67240a609a9e48fa8175d737b11896/node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaTransparentImage").default
  'NuxtPage': typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/pages/runtime/page").default
  'NoScript': typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/head/runtime/components").NoScript
  'Link': typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/head/runtime/components").Link
  'Base': typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/head/runtime/components").Base
  'Title': typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/head/runtime/components").Title
  'Meta': typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/head/runtime/components").Meta
  'Style': typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/head/runtime/components").Style
  'Head': typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/head/runtime/components").Head
  'Html': typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/head/runtime/components").Html
  'Body': typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/head/runtime/components").Body
  'NuxtIsland': typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/nuxt-island").default
  'LazyAccountPage': LazyComponent<typeof import("../../src/components/AccountsPage/AccountPage.vue").default>
  'LazyRepayDialog': LazyComponent<typeof import("../../src/components/AccountsPage/Dialogs/RepayDialog.vue").default>
  'LazyWithdrawDialog': LazyComponent<typeof import("../../src/components/AccountsPage/Dialogs/WithdrawDialog.vue").default>
  'LazyAccountBorrowTable': LazyComponent<typeof import("../../src/components/AccountsPage/Tables/AccountBorrowTable.vue").default>
  'LazyAccountBorrowTableMobile': LazyComponent<typeof import("../../src/components/AccountsPage/Tables/AccountBorrowTableMobile.vue").default>
  'LazyAccountMultiplyTable': LazyComponent<typeof import("../../src/components/AccountsPage/Tables/AccountMultiplyTable.vue").default>
  'LazyAccountSupplyTable': LazyComponent<typeof import("../../src/components/AccountsPage/Tables/AccountSupplyTable.vue").default>
  'LazyAccountSupplyTableMobile': LazyComponent<typeof import("../../src/components/AccountsPage/Tables/AccountSupplyTableMobile.vue").default>
  'LazyAppFooter': LazyComponent<typeof import("../../src/components/AppFooter.vue").default>
  'LazyAppHeader': LazyComponent<typeof import("../../src/components/AppHeader.vue").default>
  'LazyJAccordion': LazyComponent<typeof import("../../src/components/Common/JAccordion.vue").default>
  'LazyJBtn': LazyComponent<typeof import("../../src/components/Common/JBtn.vue").default>
  'LazyJBtnGroup': LazyComponent<typeof import("../../src/components/Common/JBtnGroup.vue").default>
  'LazyJCheckbox': LazyComponent<typeof import("../../src/components/Common/JCheckbox.vue").default>
  'LazyJCircularProgress': LazyComponent<typeof import("../../src/components/Common/JCircularProgress.vue").default>
  'LazyJDialog': LazyComponent<typeof import("../../src/components/Common/JDialog.vue").default>
  'LazyJDropdown': LazyComponent<typeof import("../../src/components/Common/JDropdown.vue").default>
  'LazyJInput': LazyComponent<typeof import("../../src/components/Common/JInput.vue").default>
  'LazyJLineTab': LazyComponent<typeof import("../../src/components/Common/JLineTab.vue").default>
  'LazyJLoadingSpinner': LazyComponent<typeof import("../../src/components/Common/JLoadingSpinner.vue").default>
  'LazyJPillLabel': LazyComponent<typeof import("../../src/components/Common/JPillLabel.vue").default>
  'LazyJPopover': LazyComponent<typeof import("../../src/components/Common/JPopover.vue").default>
  'LazyJSelect': LazyComponent<typeof import("../../src/components/Common/JSelect.vue").default>
  'LazyJSelectPopover': LazyComponent<typeof import("../../src/components/Common/JSelectPopover.vue").default>
  'LazyJSkeleton': LazyComponent<typeof import("../../src/components/Common/JSkeleton.vue").default>
  'LazyJToggle': LazyComponent<typeof import("../../src/components/Common/JToggle.vue").default>
  'LazyJTooltip': LazyComponent<typeof import("../../src/components/Common/JTooltip.vue").default>
  'LazyConnectWallet': LazyComponent<typeof import("../../src/components/ConnectWallet.vue").default>
  'LazyCopyToClipboard': LazyComponent<typeof import("../../src/components/CopyToClipboard.vue").default>
  'LazyCustomMixedChart': LazyComponent<typeof import("../../src/components/CustomMixedChart.vue").default>
  'LazyDynamicTeleport': LazyComponent<typeof import("../../src/components/DynamicTeleport.vue").default>
  'LazyFaucetMenu': LazyComponent<typeof import("../../src/components/FaucetMenu.vue").default>
  'LazyBorrowDialog': LazyComponent<typeof import("../../src/components/MarketsPage/Markets/Dialogs/BorrowDialog.vue").default>
  'LazySupplyDialog': LazyComponent<typeof import("../../src/components/MarketsPage/Markets/Dialogs/SupplyDialog.vue").default>
  'LazyClearFiltersBtn': LazyComponent<typeof import("../../src/components/MarketsPage/Markets/Filters/ClearFiltersBtn.vue").default>
  'LazyCollapseAllBtn': LazyComponent<typeof import("../../src/components/MarketsPage/Markets/Filters/CollapseAllBtn.vue").default>
  'LazyCollateralAssetsFilter': LazyComponent<typeof import("../../src/components/MarketsPage/Markets/Filters/CollateralAssetsFilter.vue").default>
  'LazyDebtAssetsFilter': LazyComponent<typeof import("../../src/components/MarketsPage/Markets/Filters/DebtAssetsFilter.vue").default>
  'LazyMarketSearch': LazyComponent<typeof import("../../src/components/MarketsPage/Markets/Filters/MarketSearch.vue").default>
  'LazyMarketProgress': LazyComponent<typeof import("../../src/components/MarketsPage/Markets/MarketDetailInfo/MarketProgress.vue").default>
  'LazyMarkets': LazyComponent<typeof import("../../src/components/MarketsPage/Markets/Markets.vue").default>
  'LazyMyPositionsWidget': LazyComponent<typeof import("../../src/components/MarketsPage/Markets/MyPositionsWidget.vue").default>
  'LazyMarketsList': LazyComponent<typeof import("../../src/components/MarketsPage/Markets/Tables/MarketsList.vue").default>
  'LazyMarketsListMobile': LazyComponent<typeof import("../../src/components/MarketsPage/Markets/Tables/MarketsListMobile.vue").default>
  'LazyMarketsInfo': LazyComponent<typeof import("../../src/components/MarketsPage/MarketsInfo.vue").default>
  'LazyMarketsPage': LazyComponent<typeof import("../../src/components/MarketsPage/MarketsPage.vue").default>
  'LazyMultiplyDetailTop': LazyComponent<typeof import("../../src/components/MultiplyDetailsPage/MultiplyDetailTop.vue").default>
  'LazyMultiplyDetailsPage': LazyComponent<typeof import("../../src/components/MultiplyDetailsPage/MultiplyDetailsPage.vue").default>
  'LazyMultiplyOverview': LazyComponent<typeof import("../../src/components/MultiplyDetailsPage/Overview/MultiplyOverview.vue").default>
  'LazyMultiplyForm': LazyComponent<typeof import("../../src/components/MultiplyDetailsPage/Overview/Sections/MultiplyForm.vue").default>
  'LazyMultiplyHistoryChart': LazyComponent<typeof import("../../src/components/MultiplyDetailsPage/Overview/Sections/MultiplyHistoryChart.vue").default>
  'LazyMultiplyStats': LazyComponent<typeof import("../../src/components/MultiplyDetailsPage/Overview/Sections/MultiplyStats.vue").default>
  'LazyMultiplyVault': LazyComponent<typeof import("../../src/components/MultiplyDetailsPage/Overview/Sections/MultiplyVault.vue").default>
  'LazyMultiplyPosition': LazyComponent<typeof import("../../src/components/MultiplyDetailsPage/Position/MultiplyPosition.vue").default>
  'LazyRiskWarning': LazyComponent<typeof import("../../src/components/MultiplyDetailsPage/Position/RiskWarning.vue").default>
  'LazyMyMultiplyPositions': LazyComponent<typeof import("../../src/components/MultiplyDetailsPage/Position/Sections/MyMultiplyPositions.vue").default>
  'LazyMultiplyDialog': LazyComponent<typeof import("../../src/components/MultiplyPage/Dialogs/MultiplyDialog.vue").default>
  'LazyWithdrawLeverageDialog': LazyComponent<typeof import("../../src/components/MultiplyPage/Dialogs/WithdrawLeverageDialog.vue").default>
  'LazyMultiplyApyChart': LazyComponent<typeof import("../../src/components/MultiplyPage/MultiplyApyChart.vue").default>
  'LazyMultiplyPage': LazyComponent<typeof import("../../src/components/MultiplyPage/MultiplyPage.vue").default>
  'LazyMultiplySelect': LazyComponent<typeof import("../../src/components/MultiplyPage/MultiplySelect.vue").default>
  'LazyMultiplyTable': LazyComponent<typeof import("../../src/components/MultiplyPage/Tables/MultiplyTable.vue").default>
  'LazyMultiplyTableMobile': LazyComponent<typeof import("../../src/components/MultiplyPage/Tables/MultiplyTableMobile.vue").default>
  'LazyPoolHistoryChart': LazyComponent<typeof import("../../src/components/PoolDetailPage/Charts/PoolHistoryChart.vue").default>
  'LazyPoolInterestChart': LazyComponent<typeof import("../../src/components/PoolDetailPage/Charts/PoolInterestChart.vue").default>
  'LazyPoolOverview': LazyComponent<typeof import("../../src/components/PoolDetailPage/Overview/PoolOverview.vue").default>
  'LazyPoolOverviewBottomTabs': LazyComponent<typeof import("../../src/components/PoolDetailPage/Overview/PoolOverviewBottomTabs.vue").default>
  'LazyPoolDetailOverview': LazyComponent<typeof import("../../src/components/PoolDetailPage/Overview/Sections/PoolDetailOverview.vue").default>
  'LazyPoolInfoOverview': LazyComponent<typeof import("../../src/components/PoolDetailPage/Overview/Sections/PoolInfoOverview.vue").default>
  'LazyPoolSupplyBorrowOverview': LazyComponent<typeof import("../../src/components/PoolDetailPage/Overview/Sections/PoolSupplyBorrowOverview.vue").default>
  'LazyBorrowOverview': LazyComponent<typeof import("../../src/components/PoolDetailPage/Overview/Sections/SupplyBorrow/BorrowOverview.vue").default>
  'LazySupplyOverview': LazyComponent<typeof import("../../src/components/PoolDetailPage/Overview/Sections/SupplyBorrow/SupplyOverview.vue").default>
  'LazyPoolDetailPage': LazyComponent<typeof import("../../src/components/PoolDetailPage/PoolDetailPage.vue").default>
  'LazyPoolDetailTop': LazyComponent<typeof import("../../src/components/PoolDetailPage/PoolDetailTop.vue").default>
  'LazyPoolInfoRisks': LazyComponent<typeof import("../../src/components/PoolDetailPage/PoolInfoRisks.vue").default>
  'LazyMyPosition': LazyComponent<typeof import("../../src/components/PoolDetailPage/Position/MyPosition.vue").default>
  'LazyPositionBorrowLimits': LazyComponent<typeof import("../../src/components/PoolDetailPage/Position/PositionBorrowLimits.vue").default>
  'LazyPositionOverview': LazyComponent<typeof import("../../src/components/PoolDetailPage/Position/PositionOverview.vue").default>
  'LazyPositionRiskMetrics': LazyComponent<typeof import("../../src/components/PoolDetailPage/Position/PositionRiskMetrics.vue").default>
  'LazyPositionSupplyInfo': LazyComponent<typeof import("../../src/components/PoolDetailPage/Position/PositionSupplyInfo.vue").default>
  'LazyAppSettings': LazyComponent<typeof import("../../src/components/Settings/AppSettings.vue").default>
  'LazySettingsConnect': LazyComponent<typeof import("../../src/components/Settings/Options/SettingsConnect.vue").default>
  'LazySettingsLanguage': LazyComponent<typeof import("../../src/components/Settings/Options/SettingsLanguage.vue").default>
  'LazySettingsNavigation': LazyComponent<typeof import("../../src/components/Settings/Options/SettingsNavigation.vue").default>
  'LazySettingsNetwork': LazyComponent<typeof import("../../src/components/Settings/Options/SettingsNetwork.vue").default>
  'LazySettingsRecentActivity': LazyComponent<typeof import("../../src/components/Settings/Options/SettingsRecentActivity.vue").default>
  'LazySettingsTheme': LazyComponent<typeof import("../../src/components/Settings/Options/SettingsTheme.vue").default>
  'LazySettingsSidebar': LazyComponent<typeof import("../../src/components/Settings/SettingsSidebar.vue").default>
  'LazySidebar': LazyComponent<typeof import("../../src/components/Sidebar/Sidebar.vue").default>
  'LazySidebarPanel': LazyComponent<typeof import("../../src/components/Sidebar/SidebarPanel.vue").default>
  'LazyBorrowTableSkeleton': LazyComponent<typeof import("../../src/components/Skeleton/BorrowTableSkeleton.vue").default>
  'LazyMarketInfoSkeleton': LazyComponent<typeof import("../../src/components/Skeleton/MarketInfoSkeleton.vue").default>
  'LazyMarketTableSkeleton': LazyComponent<typeof import("../../src/components/Skeleton/MarketTableSkeleton.vue").default>
  'LazyMarketTableSkeletonMobile': LazyComponent<typeof import("../../src/components/Skeleton/MarketTableSkeletonMobile.vue").default>
  'LazyPoolDetailSkeleton': LazyComponent<typeof import("../../src/components/Skeleton/PoolDetailSkeleton.vue").default>
  'LazySupplyTableSkeleton': LazyComponent<typeof import("../../src/components/Skeleton/SupplyTableSkeleton.vue").default>
  'LazyTableSkeletonMobile': LazyComponent<typeof import("../../src/components/Skeleton/TableSkeletonMobile.vue").default>
  'LazyBorrowWindow': LazyComponent<typeof import("../../src/components/SupplyCard/BorrowWindow.vue").default>
  'LazyChangePoolDialog': LazyComponent<typeof import("../../src/components/SupplyCard/ChangePoolDialog.vue").default>
  'LazyRepayWindow': LazyComponent<typeof import("../../src/components/SupplyCard/RepayWindow.vue").default>
  'LazySupplyCard': LazyComponent<typeof import("../../src/components/SupplyCard/SupplyCard.vue").default>
  'LazySupplyWindow': LazyComponent<typeof import("../../src/components/SupplyCard/SupplyWindow.vue").default>
  'LazyWithdrawWindow': LazyComponent<typeof import("../../src/components/SupplyCard/WithdrawWindow.vue").default>
  'LazyAddressIcon': LazyComponent<typeof import("../../src/components/Widget/AddressIcon.vue").default>
  'LazyBackBtn': LazyComponent<typeof import("../../src/components/Widget/BackBtn.vue").default>
  'LazyChartDateFilter': LazyComponent<typeof import("../../src/components/Widget/ChartDateFilter.vue").default>
  'LazyInfoPanel': LazyComponent<typeof import("../../src/components/Widget/InfoPanel.vue").default>
  'LazyInfoTooltip': LazyComponent<typeof import("../../src/components/Widget/InfoTooltip.vue").default>
  'LazyInputWidget': LazyComponent<typeof import("../../src/components/Widget/InputWidget.vue").default>
  'LazyLightingApy': LazyComponent<typeof import("../../src/components/Widget/LightingApy.vue").default>
  'LazyLogoWithText': LazyComponent<typeof import("../../src/components/Widget/LogoWithText.vue").default>
  'LazyMarketDialogActionBtn': LazyComponent<typeof import("../../src/components/Widget/MarketDialogActionBtn.vue").default>
  'LazyMarketInfoBadge': LazyComponent<typeof import("../../src/components/Widget/MarketInfoBadge.vue").default>
  'LazyMarketInfoDetailCard': LazyComponent<typeof import("../../src/components/Widget/MarketInfoDetailCard.vue").default>
  'LazyMetricIndicator': LazyComponent<typeof import("../../src/components/Widget/MetricIndicator.vue").default>
  'LazyPoolStatus': LazyComponent<typeof import("../../src/components/Widget/PoolStatus.vue").default>
  'LazyReloadCoundown': LazyComponent<typeof import("../../src/components/Widget/ReloadCoundown.vue").default>
  'LazyTableMobileCard': LazyComponent<typeof import("../../src/components/Widget/TableMobileCard.vue").default>
  'LazyTotalCard': LazyComponent<typeof import("../../src/components/Widget/TotalCard.vue").default>
  'LazyWarningBlock': LazyComponent<typeof import("../../src/components/Widget/WarningBlock.vue").default>
  'LazyNuxtWelcome': LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/welcome.vue").default>
  'LazyNuxtLayout': LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/nuxt-layout").default>
  'LazyNuxtErrorBoundary': LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default>
  'LazyClientOnly': LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/client-only").default>
  'LazyDevOnly': LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/dev-only").default>
  'LazyServerPlaceholder': LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/server-placeholder").default>
  'LazyNuxtLink': LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/nuxt-link").default>
  'LazyNuxtLoadingIndicator': LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default>
  'LazyNuxtTime': LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/nuxt-time.vue").default>
  'LazyNuxtRouteAnnouncer': LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/nuxt-route-announcer").default>
  'LazyNuxtImg': LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtImg>
  'LazyNuxtPicture': LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtPicture>
  'LazyBAccordion': LazyComponent<typeof import("bootstrap-vue-next/components/BAccordion").BAccordion>
  'LazyBAccordionItem': LazyComponent<typeof import("bootstrap-vue-next/components/BAccordion").BAccordionItem>
  'LazyBAlert': LazyComponent<typeof import("bootstrap-vue-next/components/BAlert").BAlert>
  'LazyBAvatar': LazyComponent<typeof import("bootstrap-vue-next/components/BAvatar").BAvatar>
  'LazyBAvatarGroup': LazyComponent<typeof import("bootstrap-vue-next/components/BAvatar").BAvatarGroup>
  'LazyBBadge': LazyComponent<typeof import("bootstrap-vue-next/components/BBadge").BBadge>
  'LazyBBreadcrumb': LazyComponent<typeof import("bootstrap-vue-next/components/BBreadcrumb").BBreadcrumb>
  'LazyBBreadcrumbItem': LazyComponent<typeof import("bootstrap-vue-next/components/BBreadcrumb").BBreadcrumbItem>
  'LazyBButton': LazyComponent<typeof import("bootstrap-vue-next/components/BButton").BButton>
  'LazyBButtonGroup': LazyComponent<typeof import("bootstrap-vue-next/components/BButton").BButtonGroup>
  'LazyBButtonToolbar': LazyComponent<typeof import("bootstrap-vue-next/components/BButton").BButtonToolbar>
  'LazyBCloseButton': LazyComponent<typeof import("bootstrap-vue-next/components/BButton").BCloseButton>
  'LazyBCard': LazyComponent<typeof import("bootstrap-vue-next/components/BCard").BCard>
  'LazyBCardBody': LazyComponent<typeof import("bootstrap-vue-next/components/BCard").BCardBody>
  'LazyBCardFooter': LazyComponent<typeof import("bootstrap-vue-next/components/BCard").BCardFooter>
  'LazyBCardGroup': LazyComponent<typeof import("bootstrap-vue-next/components/BCard").BCardGroup>
  'LazyBCardHeader': LazyComponent<typeof import("bootstrap-vue-next/components/BCard").BCardHeader>
  'LazyBCardImg': LazyComponent<typeof import("bootstrap-vue-next/components/BCard").BCardImg>
  'LazyBCardSubtitle': LazyComponent<typeof import("bootstrap-vue-next/components/BCard").BCardSubtitle>
  'LazyBCardText': LazyComponent<typeof import("bootstrap-vue-next/components/BCard").BCardText>
  'LazyBCardTitle': LazyComponent<typeof import("bootstrap-vue-next/components/BCard").BCardTitle>
  'LazyBCarousel': LazyComponent<typeof import("bootstrap-vue-next/components/BCarousel").BCarousel>
  'LazyBCarouselSlide': LazyComponent<typeof import("bootstrap-vue-next/components/BCarousel").BCarouselSlide>
  'LazyBCol': LazyComponent<typeof import("bootstrap-vue-next/components/BContainer").BCol>
  'LazyBCollapse': LazyComponent<typeof import("bootstrap-vue-next/components/BCollapse").BCollapse>
  'LazyBContainer': LazyComponent<typeof import("bootstrap-vue-next/components/BContainer").BContainer>
  'LazyBDropdown': LazyComponent<typeof import("bootstrap-vue-next/components/BDropdown").BDropdown>
  'LazyBDropdownDivider': LazyComponent<typeof import("bootstrap-vue-next/components/BDropdown").BDropdownDivider>
  'LazyBDropdownForm': LazyComponent<typeof import("bootstrap-vue-next/components/BDropdown").BDropdownForm>
  'LazyBDropdownGroup': LazyComponent<typeof import("bootstrap-vue-next/components/BDropdown").BDropdownGroup>
  'LazyBDropdownHeader': LazyComponent<typeof import("bootstrap-vue-next/components/BDropdown").BDropdownHeader>
  'LazyBDropdownItem': LazyComponent<typeof import("bootstrap-vue-next/components/BDropdown").BDropdownItem>
  'LazyBDropdownItemButton': LazyComponent<typeof import("bootstrap-vue-next/components/BDropdown").BDropdownItemButton>
  'LazyBDropdownText': LazyComponent<typeof import("bootstrap-vue-next/components/BDropdown").BDropdownText>
  'LazyBForm': LazyComponent<typeof import("bootstrap-vue-next/components/BForm").BForm>
  'LazyBFormCheckbox': LazyComponent<typeof import("bootstrap-vue-next/components/BFormCheckbox").BFormCheckbox>
  'LazyBFormCheckboxGroup': LazyComponent<typeof import("bootstrap-vue-next/components/BFormCheckbox").BFormCheckboxGroup>
  'LazyBFormDatalist': LazyComponent<typeof import("bootstrap-vue-next/components/BForm").BFormDatalist>
  'LazyBFormFile': LazyComponent<typeof import("bootstrap-vue-next/components/BFormFile").BFormFile>
  'LazyBFormFloatingLabel': LazyComponent<typeof import("bootstrap-vue-next/components/BForm").BFormFloatingLabel>
  'LazyBFormGroup': LazyComponent<typeof import("bootstrap-vue-next/components/BFormGroup").BFormGroup>
  'LazyBFormInput': LazyComponent<typeof import("bootstrap-vue-next/components/BFormInput").BFormInput>
  'LazyBFormInvalidFeedback': LazyComponent<typeof import("bootstrap-vue-next/components/BForm").BFormInvalidFeedback>
  'LazyBFormRadio': LazyComponent<typeof import("bootstrap-vue-next/components/BFormRadio").BFormRadio>
  'LazyBFormRadioGroup': LazyComponent<typeof import("bootstrap-vue-next/components/BFormRadio").BFormRadioGroup>
  'LazyBFormRating': LazyComponent<typeof import("bootstrap-vue-next/components/BFormRating").BFormRating>
  'LazyBFormRow': LazyComponent<typeof import("bootstrap-vue-next/components/BForm").BFormRow>
  'LazyBFormSelect': LazyComponent<typeof import("bootstrap-vue-next/components/BFormSelect").BFormSelect>
  'LazyBFormSelectOption': LazyComponent<typeof import("bootstrap-vue-next/components/BFormSelect").BFormSelectOption>
  'LazyBFormSelectOptionGroup': LazyComponent<typeof import("bootstrap-vue-next/components/BFormSelect").BFormSelectOptionGroup>
  'LazyBFormSpinbutton': LazyComponent<typeof import("bootstrap-vue-next/components/BFormSpinbutton").BFormSpinbutton>
  'LazyBFormTag': LazyComponent<typeof import("bootstrap-vue-next/components/BFormTags").BFormTag>
  'LazyBFormTags': LazyComponent<typeof import("bootstrap-vue-next/components/BFormTags").BFormTags>
  'LazyBFormText': LazyComponent<typeof import("bootstrap-vue-next/components/BForm").BFormText>
  'LazyBFormTextarea': LazyComponent<typeof import("bootstrap-vue-next/components/BFormTextarea").BFormTextarea>
  'LazyBFormValidFeedback': LazyComponent<typeof import("bootstrap-vue-next/components/BForm").BFormValidFeedback>
  'LazyBImg': LazyComponent<typeof import("bootstrap-vue-next/components/BImg").BImg>
  'LazyBInput': LazyComponent<typeof import("bootstrap-vue-next/components/BFormInput").BInput>
  'LazyBInputGroup': LazyComponent<typeof import("bootstrap-vue-next/components/BInputGroup").BInputGroup>
  'LazyBInputGroupText': LazyComponent<typeof import("bootstrap-vue-next/components/BInputGroup").BInputGroupText>
  'LazyBListGroup': LazyComponent<typeof import("bootstrap-vue-next/components/BListGroup").BListGroup>
  'LazyBListGroupItem': LazyComponent<typeof import("bootstrap-vue-next/components/BListGroup").BListGroupItem>
  'LazyBModal': LazyComponent<typeof import("bootstrap-vue-next/components/BModal").BModal>
  'LazyBModalOrchestrator': LazyComponent<typeof import("bootstrap-vue-next/components/BModal").BModalOrchestrator>
  'LazyBNav': LazyComponent<typeof import("bootstrap-vue-next/components/BNav").BNav>
  'LazyBNavForm': LazyComponent<typeof import("bootstrap-vue-next/components/BNav").BNavForm>
  'LazyBNavItem': LazyComponent<typeof import("bootstrap-vue-next/components/BNav").BNavItem>
  'LazyBNavItemDropdown': LazyComponent<typeof import("bootstrap-vue-next/components/BNav").BNavItemDropdown>
  'LazyBNavText': LazyComponent<typeof import("bootstrap-vue-next/components/BNav").BNavText>
  'LazyBNavbar': LazyComponent<typeof import("bootstrap-vue-next/components/BNavbar").BNavbar>
  'LazyBNavbarBrand': LazyComponent<typeof import("bootstrap-vue-next/components/BNavbar").BNavbarBrand>
  'LazyBNavbarNav': LazyComponent<typeof import("bootstrap-vue-next/components/BNavbar").BNavbarNav>
  'LazyBNavbarToggle': LazyComponent<typeof import("bootstrap-vue-next/components/BNavbar").BNavbarToggle>
  'LazyBOffcanvas': LazyComponent<typeof import("bootstrap-vue-next/components/BOffcanvas").BOffcanvas>
  'LazyBOverlay': LazyComponent<typeof import("bootstrap-vue-next/components/BOverlay").BOverlay>
  'LazyBPagination': LazyComponent<typeof import("bootstrap-vue-next/components/BPagination").BPagination>
  'LazyBPlaceholder': LazyComponent<typeof import("bootstrap-vue-next/components/BPlaceholder").BPlaceholder>
  'LazyBPlaceholderButton': LazyComponent<typeof import("bootstrap-vue-next/components/BPlaceholder").BPlaceholderButton>
  'LazyBPlaceholderCard': LazyComponent<typeof import("bootstrap-vue-next/components/BPlaceholder").BPlaceholderCard>
  'LazyBPlaceholderTable': LazyComponent<typeof import("bootstrap-vue-next/components/BPlaceholder").BPlaceholderTable>
  'LazyBPlaceholderWrapper': LazyComponent<typeof import("bootstrap-vue-next/components/BPlaceholder").BPlaceholderWrapper>
  'LazyBPopover': LazyComponent<typeof import("bootstrap-vue-next/components/BPopover").BPopover>
  'LazyBProgress': LazyComponent<typeof import("bootstrap-vue-next/components/BProgress").BProgress>
  'LazyBRow': LazyComponent<typeof import("bootstrap-vue-next/components/BContainer").BRow>
  'LazyBSpinner': LazyComponent<typeof import("bootstrap-vue-next/components/BSpinner").BSpinner>
  'LazyBTab': LazyComponent<typeof import("bootstrap-vue-next/components/BTabs").BTab>
  'LazyBTabs': LazyComponent<typeof import("bootstrap-vue-next/components/BTabs").BTabs>
  'LazyBToast': LazyComponent<typeof import("bootstrap-vue-next/components/BToast").BToast>
  'LazyBToastOrchestrator': LazyComponent<typeof import("bootstrap-vue-next/components/BToast").BToastOrchestrator>
  'LazyBTooltip': LazyComponent<typeof import("bootstrap-vue-next/components/BTooltip").BTooltip>
  'LazyBLink': LazyComponent<typeof import("bootstrap-vue-next/components/BLink").BLink>
  'LazyBProgressBar': LazyComponent<typeof import("bootstrap-vue-next/components/BProgress").BProgressBar>
  'LazyBTableSimple': LazyComponent<typeof import("bootstrap-vue-next/components/BTable").BTableSimple>
  'LazyBTableLite': LazyComponent<typeof import("bootstrap-vue-next/components/BTable").BTableLite>
  'LazyBTable': LazyComponent<typeof import("bootstrap-vue-next/components/BTable").BTable>
  'LazyBTbody': LazyComponent<typeof import("bootstrap-vue-next/components/BTable").BTbody>
  'LazyBTd': LazyComponent<typeof import("bootstrap-vue-next/components/BTable").BTd>
  'LazyBTh': LazyComponent<typeof import("bootstrap-vue-next/components/BTable").BTh>
  'LazyBThead': LazyComponent<typeof import("bootstrap-vue-next/components/BTable").BThead>
  'LazyBTfoot': LazyComponent<typeof import("bootstrap-vue-next/components/BTable").BTfoot>
  'LazyBTr': LazyComponent<typeof import("bootstrap-vue-next/components/BTable").BTr>
  'LazyBPopoverOrchestrator': LazyComponent<typeof import("bootstrap-vue-next/components/BPopover").BPopoverOrchestrator>
  'LazyNuxtLinkLocale': LazyComponent<typeof import("../../../../node_modules/.pnpm/@nuxtjs+i18n@10.2.1_@vue+compiler-dom@3.5.27_db0@0.3.4_eslint@9.39.2_jiti@2.6.1__idb-ke_d844bff0289b9fea1b2ee74a046c285f/node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale").default>
  'LazySwitchLocalePathLink': LazyComponent<typeof import("../../../../node_modules/.pnpm/@nuxtjs+i18n@10.2.1_@vue+compiler-dom@3.5.27_db0@0.3.4_eslint@9.39.2_jiti@2.6.1__idb-ke_d844bff0289b9fea1b2ee74a046c285f/node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink").default>
  'LazyVitePwaManifest': LazyComponent<typeof import("../../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.0_magicast@0.5.1_vite@7.3.1_@types+node@24.10.9_jiti@2.6.1_sass-embe_3c67240a609a9e48fa8175d737b11896/node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest").default>
  'LazyNuxtPwaManifest': LazyComponent<typeof import("../../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.0_magicast@0.5.1_vite@7.3.1_@types+node@24.10.9_jiti@2.6.1_sass-embe_3c67240a609a9e48fa8175d737b11896/node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest").default>
  'LazyNuxtPwaAssets': LazyComponent<typeof import("../../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.0_magicast@0.5.1_vite@7.3.1_@types+node@24.10.9_jiti@2.6.1_sass-embe_3c67240a609a9e48fa8175d737b11896/node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets").default>
  'LazyPwaAppleImage': LazyComponent<typeof import("../../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.0_magicast@0.5.1_vite@7.3.1_@types+node@24.10.9_jiti@2.6.1_sass-embe_3c67240a609a9e48fa8175d737b11896/node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaAppleImage").default>
  'LazyPwaAppleSplashScreenImage': LazyComponent<typeof import("../../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.0_magicast@0.5.1_vite@7.3.1_@types+node@24.10.9_jiti@2.6.1_sass-embe_3c67240a609a9e48fa8175d737b11896/node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaAppleSplashScreenImage").default>
  'LazyPwaFaviconImage': LazyComponent<typeof import("../../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.0_magicast@0.5.1_vite@7.3.1_@types+node@24.10.9_jiti@2.6.1_sass-embe_3c67240a609a9e48fa8175d737b11896/node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaFaviconImage").default>
  'LazyPwaMaskableImage': LazyComponent<typeof import("../../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.0_magicast@0.5.1_vite@7.3.1_@types+node@24.10.9_jiti@2.6.1_sass-embe_3c67240a609a9e48fa8175d737b11896/node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaMaskableImage").default>
  'LazyPwaTransparentImage': LazyComponent<typeof import("../../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.0_magicast@0.5.1_vite@7.3.1_@types+node@24.10.9_jiti@2.6.1_sass-embe_3c67240a609a9e48fa8175d737b11896/node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaTransparentImage").default>
  'LazyNuxtPage': LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/pages/runtime/page").default>
  'LazyNoScript': LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/head/runtime/components").NoScript>
  'LazyLink': LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/head/runtime/components").Link>
  'LazyBase': LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/head/runtime/components").Base>
  'LazyTitle': LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/head/runtime/components").Title>
  'LazyMeta': LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/head/runtime/components").Meta>
  'LazyStyle': LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/head/runtime/components").Style>
  'LazyHead': LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/head/runtime/components").Head>
  'LazyHtml': LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/head/runtime/components").Html>
  'LazyBody': LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/head/runtime/components").Body>
  'LazyNuxtIsland': LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/components/nuxt-island").default>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
