// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../../../node_modules/.pnpm/@pinia+nuxt@0.11.3_magicast@0.5.1_pinia@3.0.4_typescript@5.9.3_vue@3.5.27_typescript@5.9.3__/node_modules/@pinia/nuxt/dist/runtime/payload-plugin.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/head/runtime/plugins/unhead.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/pages/runtime/plugins/router.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/plugins/browser-devtools-timing.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/plugins/payload.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/plugins/dev-server-logs.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@pinia+nuxt@0.11.3_magicast@0.5.1_pinia@3.0.4_typescript@5.9.3_vue@3.5.27_typescript@5.9.3__/node_modules/@pinia/nuxt/dist/runtime/plugin.vue3.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/pages/runtime/plugins/check-if-page-unused.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxt+devtools@3.1.1_bufferutil@4.1.0_utf-8-validate@5.0.10_vite@7.3.1_@types+node@24.1_481b9872eccfaccdec58431bbf4b8f80/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.server.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxt+devtools@3.1.1_bufferutil@4.1.0_utf-8-validate@5.0.10_vite@7.3.1_@types+node@24.1_481b9872eccfaccdec58431bbf4b8f80/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client.js")> &
  InjectionType<typeof import("../pwa-icons-plugin")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxtjs+i18n@10.2.1_@vue+compiler-dom@3.5.27_db0@0.3.4_eslint@9.39.2_jiti@2.6.1__idb-ke_d844bff0289b9fea1b2ee74a046c285f/node_modules/@nuxtjs/i18n/dist/runtime/plugins/switch-locale-path-ssr.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxtjs+i18n@10.2.1_@vue+compiler-dom@3.5.27_db0@0.3.4_eslint@9.39.2_jiti@2.6.1__idb-ke_d844bff0289b9fea1b2ee74a046c285f/node_modules/@nuxtjs/i18n/dist/runtime/plugins/route-locale-detect.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxtjs+i18n@10.2.1_@vue+compiler-dom@3.5.27_db0@0.3.4_eslint@9.39.2_jiti@2.6.1__idb-ke_d844bff0289b9fea1b2ee74a046c285f/node_modules/@nuxtjs/i18n/dist/runtime/plugins/preload.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxtjs+i18n@10.2.1_@vue+compiler-dom@3.5.27_db0@0.3.4_eslint@9.39.2_jiti@2.6.1__idb-ke_d844bff0289b9fea1b2ee74a046c285f/node_modules/@nuxtjs/i18n/dist/runtime/plugins/dev.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxtjs+i18n@10.2.1_@vue+compiler-dom@3.5.27_db0@0.3.4_eslint@9.39.2_jiti@2.6.1__idb-ke_d844bff0289b9fea1b2ee74a046c285f/node_modules/@nuxtjs/i18n/dist/runtime/plugins/i18n.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@bootstrap-vue-next+nuxt@0.30.5_bootstrap-vue-next@0.30.3_@floating-ui+vue@1.1.9_vue@3._6855f7aa8d95be36557ec79d4bbea8ef/node_modules/@bootstrap-vue-next/nuxt/dist/runtime/useDirectives.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@bootstrap-vue-next+nuxt@0.30.5_bootstrap-vue-next@0.30.3_@floating-ui+vue@1.1.9_vue@3._6855f7aa8d95be36557ec79d4bbea8ef/node_modules/@bootstrap-vue-next/nuxt/dist/runtime/createBootstrap.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/plugins/warn.dev.server.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/plugins/check-if-layout-used.js")> &
  InjectionType<typeof import("../../src/plugins/nprogress.client")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.0_magicast@0.5.1_vite@7.3.1_@types+node@24.10.9_jiti@2.6.1_sass-embe_3c67240a609a9e48fa8175d737b11896/node_modules/@vite-pwa/nuxt/dist/runtime/plugins/pwa.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxtjs+i18n@10.2.1_@vue+compiler-dom@3.5.27_db0@0.3.4_eslint@9.39.2_jiti@2.6.1__idb-ke_d844bff0289b9fea1b2ee74a046c285f/node_modules/@nuxtjs/i18n/dist/runtime/plugins/ssg-detect.js")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'vue-devtools-client' | 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt:browser-devtools-timing' | 'nuxt:payload' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'pinia' | 'nuxt:global-components' | 'nuxt:prefetch' | 'nuxt:checkIfPageUnused' | 'vite-pwa:nuxt:pwa-icons-plugin' | 'i18n:plugin:switch-locale-path-ssr' | 'i18n:plugin:route-locale-detect' | 'i18n:plugin:preload' | 'i18n:dev' | 'i18n:plugin' | 'nuxt:checkIfLayoutUsed' | 'vite-pwa:nuxt:client:plugin' | 'i18n:plugin:ssg-detect'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
