// Generated by auto imports
export {}
declare global {
  const createError: typeof import('../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/composables/error').createError
  const defineAppConfig: typeof import('../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/nuxt').defineAppConfig
  const defineI18nConfig: typeof import('../../../../node_modules/.pnpm/@nuxtjs+i18n@10.2.1_@vue+compiler-dom@3.5.27_db0@0.3.4_eslint@9.39.2_jiti@2.6.1__idb-ke_d844bff0289b9fea1b2ee74a046c285f/node_modules/@nuxtjs/i18n/dist/runtime/composables/index').defineI18nConfig
  const defineI18nLocale: typeof import('../../../../node_modules/.pnpm/@nuxtjs+i18n@10.2.1_@vue+compiler-dom@3.5.27_db0@0.3.4_eslint@9.39.2_jiti@2.6.1__idb-ke_d844bff0289b9fea1b2ee74a046c285f/node_modules/@nuxtjs/i18n/dist/runtime/composables/index').defineI18nLocale
  const getRouteRules: typeof import('../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/composables/manifest').getRouteRules
  const setResponseStatus: typeof import('../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/composables/ssr').setResponseStatus
  const useAppConfig: typeof import('../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/config').useAppConfig
  const useRuntimeConfig: typeof import('../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@types+node@24.10.9_@vue+compiler-sfc@3.5.27_bufferuti_f6673406927cf53a62d3db8723fb7518/node_modules/nuxt/dist/app/nuxt').useRuntimeConfig
}